import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,groundAt,copyProjectileTerrain} from '../src/core.js';
import {forecastProjectileContact} from '../src/combat-presentation.js';
import {ARROW_LENGTH,projectilePoint} from '../src/projectile-shape.js';
import {arrowGeometry} from '../src/projectile-geometry.js';
import {createDetailedActor} from '../src/actor-models.js';
import {inspectLoadedArrow} from '../scripts/verify-loaded-arrow.mjs';
import {inspectProjectileBudget} from '../scripts/verify-projectile-budget.mjs';
const close=(a,b,e=1e-8)=>assert(Math.abs(a-b)<e,`${a} != ${b}`);
function fixture(){const g=new Game();g.enemies.forEach(e=>e.dead=true);g.obstacles=[];g.events=[];Object.assign(g.player,{x:0,z:86,y:groundAt(0,86),hp:120,invulnerable:0,angle:0});return g;}
function arrow(g,d=12){return {id:1,owner:g.enemies.find(e=>e.type==='ranger').id,x:0,y:g.player.y+1,z:86+d,vx:0,vy:0,vz:-19,life:2.3,damage:20};}
function replay(g,a,hz){a={...a};let elapsed=0;while(a.life>1/hz){const c=g.projectileContact(a,1/hz);if(c.target)return {target:c.target,time:elapsed+c.fraction/hz,point:c.point};Object.assign(a,c.to);a.life-=1/hz;elapsed+=1/hz;}return null;}
test('tail, loaded and flying extent preserve full length with a narrow nock',()=>{const {shaft,tip}=arrowGeometry();shaft.computeBoundingBox();tip.computeBoundingBox();close(shaft.boundingBox.min.z,0);close(shaft.boundingBox.max.z,1.1,1e-6);close(tip.boundingBox.max.z,ARROW_LENGTH,1e-6);close(shaft.boundingBox.max.x,.0225,1e-6);shaft.dispose();tip.dispose();const r=inspectLoadedArrow();assert.equal(r.rows.length,45);assert(r.rows.every(p=>p.hits.length===0&&p.tailGap<1e-6&&Math.abs(p.length-ARROW_LENGTH)<1e-6&&Math.abs(p.gripOffset-.12)<1e-6));assert(r.rows.every(p=>p.triangles===7108&&p.meshes===12));});
test('full initial occupied span resolves wall and body by raw distance before t0 conversion',()=>{for(const hz of[30,60,120])for(const d of[.15,.5,1,1.3]){const g=fixture(),a=arrow(g);g.obstacles=[{x:0,z:a.z-d-.2,y:a.y-1,r:.2,height:3}];const c=g.projectileContact(a,1/hz);assert.equal(c.target,'wall');assert.equal(c.fraction,0);close(c.point.z,a.z-d+.08);assert.equal(forecastProjectileContact(g,a,1.8).target,'wall');}
 for(const wallDistance of[.1,.6]){const g=fixture(),a=arrow(g,.8);g.obstacles=[{x:0,z:a.z-wallDistance-.03,y:a.y-1,r:.03,height:3}];const c=g.projectileContact(a,1/60);assert.equal(c.fraction,0);assert.equal(c.target,wallDistance===.1?'wall':g.player);}
});
test('all rates and optimized prediction use the leading tip time while damage stays 20',()=>{for(const hz of[30,60,120]){const g=fixture(),a=arrow(g),hit=replay(g,a,hz),f=forecastProjectileContact(g,a,1.8);assert.equal(hit.target,g.player);close(hit.time,(12-.6-ARROW_LENGTH)/19);close(f.timeToImpact,hit.time);g.projectiles=[a];for(let i=0;i<120&&g.projectiles.length;i++)g.tickProjectiles(1/hz);assert.equal(g.player.hp,100);assert.equal(g.projectiles.length,0);}});
test('a moving actor inside the current shaft is detected even behind its tip',()=>{const g=fixture(),a=arrow(g,1);const c=g.projectileContact(a,1/120);assert.equal(c.target,g.player);assert.equal(c.fraction,0);const tip=projectilePoint(a,0,ARROW_LENGTH);assert(tip.z<g.player.z);});
test('terrain continuation is copied to forecasts and rejected after a teleport or reversal',()=>{const g=fixture(),a={...arrow(g),y:20},first=g.projectileContact(a,1/60);assert.equal(first.target,null);Object.assign(a,first.to);const saved=JSON.stringify(a),copy={...a};copyProjectileTerrain(a,copy);const next=g.projectileContact(a,1/60);assert.deepEqual(g.projectileContact(copy,1/60),next);assert.equal(JSON.stringify(a),saved);Object.assign(a,next.to);a.y=groundAt(a.x,a.z)-.1;const teleported=g.projectileContact(a,1/60);assert.equal(teleported.target,'wall');assert.equal(teleported.fraction,0);a.y=20;a.vz=19;assert.equal(g.projectileContact(a,1/60).target,null);});
test('parry uses contact as outgoing tail and checks reflected cover immediately',()=>{for(const covered of[false,true]){const g=fixture(),p=g.player,source=g.enemies.find(e=>e.type==='ranger');Object.assign(source,{dead:false,x:8,z:90,y:p.y,hp:100});p.parry=.48;const a=arrow(g,.8),c=g.projectileContact(a,1/30),dx=source.x-c.point.x,dy=source.y+1.2-c.point.y,dz=source.z-c.point.z,s=Math.hypot(dx,dy,dz);if(covered)g.obstacles=[{x:c.point.x+dx/s*.65,z:c.point.z+dz/s*.65,y:p.y,r:.1,height:3}];g.projectiles=[a];g.tickProjectiles(1/30);assert.equal(p.hp,120);assert(g.events.some(e=>e.type==='perfect'));if(covered){assert.equal(g.projectiles.length,0);const event=g.events.find(e=>e.type==='arrowBreak');assert(event.x>.1);}else{assert.equal(a.owner,'player');close(a.x,c.point.x);close(a.z,c.point.z);close(Math.hypot(a.vx,a.vy,a.vz),25);assert.equal(a.life,2);assert.equal(a.damage,g.damageAmount()*1.5);}}});
test('expiry, saved coordinates and arrows after shooter death retain their contracts',()=>{for(const hz of[30,60,120])for(const life of[.01,.02,.04]){const g=fixture(),a={...arrow(g,.8),life};g.projectiles=[a];g.tickProjectiles(1/hz);assert.equal(g.player.hp,life>1/hz?100:120);assert.equal(g.projectiles.length,0);}
 const g=fixture(),a=arrow(g),source=g.enemies.find(e=>e.id===a.owner);Object.assign(source,{dead:false,hp:1});g.projectiles=[a];g.hurtEnemy(source,10);g.tickProjectiles(1/60);assert.equal(g.projectiles.length,1);const copy=new Game(g.serialize()).projectiles[0];for(const k of['x','y','z','vx','vy','vz','life','damage','owner'])assert.equal(copy[k],a[k]);
});
test('a second real ranger windup shows its loaded arrow despite the previous hit flag',()=>{const g=fixture(),e=g.enemies.find(e=>e.type==='ranger');Object.assign(e,{dead:false,state:'chase',cooldown:0,hp:100});Object.assign(g.player,{x:e.x,z:e.z+12,y:groundAt(e.x,e.z+12)});const a=createDetailedActor('ranger');let staleWindup=0,firstWindup=0,hiddenRelease=0;for(let i=0;i<480&&g.projectiles.length<3;i++){g.tickEnemy(e,1/60);a.g.position.set(e.x,e.y,e.z);a.g.rotation.y=e.angle;a.animate(e,1/60);if(e.state==='windup'&&a.motion.combat?.bowHold>.98){assert(a.archery.arrow.scale.x>0);if(e.hit)staleWindup++;else firstWindup++;}if(e.state==='strike'&&e.hit){assert.equal(a.archery.arrow.scale.x,0);hiddenRelease++;}}assert(g.projectiles.length>=2);assert(firstWindup>0&&staleWindup>0&&hiddenRelease>0);});
test('same instrumented 48-arrow budget includes exact terrain work and rejects full-span resampling',async()=>{const r=await inspectProjectileBudget();assert.equal(r.baseline.actualTerrainReads,1618);assert.equal(r.candidate.actualTerrainReads,1522);assert.equal(r.fullSpan.actualTerrainReads,5690);});
