import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';
import { WORLD_POINTS, objectiveFor, terrainHeight } from '../src/core.js';
import { World } from '../src/world.js';

test('procedural world builds a continuous local scene with every required destination', () => {
  const scene = new THREE.Scene();
  const world = new World(scene, 2);
  assert.equal(scene.getObjectByName('WILDBOUND_WORLD'), world.root);
  assert.ok(world.terrain.geometry.attributes.position.count >= 16000);
  assert.equal(world.discovery.size, WORLD_POINTS.length);
  for (const point of WORLD_POINTS) {
    const landmark = world.discovery.get(point.id);
    assert.ok(landmark, `${point.id} landmark exists`);
    assert.equal(landmark.group.position.x, point.x);
    assert.equal(landmark.group.position.y, terrainHeight(point.x, point.z));
  }
  assert.ok(world.trunks.count >= 500, 'forest density is substantial');
  assert.ok(world.grass.count >= 1500, 'grassland detail is populated');
  assert.ok(world.interactables.length >= 45, 'world includes NPC, camp, lore, cache, and resources');
  assert.ok(world.interactables.some(item => item.type === 'npc'));
  assert.ok(world.interactables.some(item => item.type === 'camp'));
  assert.ok(world.interactables.some(item => item.type === 'herb'));
  assert.ok(world.interactables.some(item => item.type === 'crystal'));
  assert.equal(world.blockers.length, 5, 'village houses register deterministic navigation footprints');
  assert.equal(world.isBlocked(-27, 252, 1), true);
  assert.equal(world.isBlocked(80, 270, 1), false);
  assert.ok(world.npcs.length >= 5, 'Mira, Orin, and Ilya have persistent and aftermath actor rigs');
  for (const npc of world.npcs) {
    assert.equal(npc.userData.rig?.kind, 'humanoid');
    assert.equal(npc.userData.rig?.arms.length, 2);
    assert.equal(npc.userData.rig?.legs.length, 2);
  }
  world.dispose();
  assert.equal(scene.getObjectByName('WILDBOUND_WORLD'), undefined);
});

test('quality controls and objective marker change the runnable scene', () => {
  const scene = new THREE.Scene();
  const world = new World(scene, 2);
  assert.equal(world.fireflies.visible, true);
  world.setQuality(0);
  assert.equal(world.clouds.visible, false);
  assert.equal(world.grass.visible, false);
  assert.equal(world.flowers.visible, false);
  assert.equal(world.fireflies.visible, false);
  const target = objectiveFor({ story: 0, sigils: [], victory: false });
  world.setObjective(target);
  assert.equal(world.objective.group.visible, true);
  assert.equal(world.objective.group.position.x, target.x);
  world.setObjective(null);
  assert.equal(world.objective.group.visible, false);
  world.setChoices({ grove: 'haven_ward' });
  assert.equal(world.choiceVisuals.havenWard.visible, true);
  assert.equal(world.choiceVisuals.wildBloom.visible, false);
  world.setChoices({ grove: 'wild_bloom' });
  assert.equal(world.choiceVisuals.havenWard.visible, false);
  assert.equal(world.choiceVisuals.wildBloom.visible, true);
  world.setChoices({ marsh: 'water_ward', peak: 'wind_release' });
  assert.equal(world.choiceVisuals.waterWard.visible, true);
  assert.equal(world.choiceVisuals.ringRelease.visible, false);
  assert.equal(world.choiceVisuals.windWard.visible, false);
  assert.equal(world.choiceVisuals.windRelease.visible, true);
  world.setChoices({ marsh: 'ring_release', peak: 'wind_ward' });
  assert.equal(world.choiceVisuals.waterWard.visible, false);
  assert.equal(world.choiceVisuals.ringRelease.visible, true);
  assert.equal(world.choiceVisuals.windWard.visible, true);
  assert.equal(world.choiceVisuals.windRelease.visible, false);
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: '', peak: '' }, defeated: ['grove_warden'], npcFlags: {} });
  assert.equal(world.storyScenes.mira.group.visible, true);
  assert.equal(world.storyScenes.mira.wild.visible, true);
  assert.equal(world.storyScenes.miraTrace.group.visible, false);
  assert.equal(world.miraNpc.visible, false, 'Mira moves from the village into the playable aftermath scene');
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: '', peak: '' }, defeated: ['grove_warden'], characterQuests: { mira: 1 }, npcFlags: {} });
  assert.equal(world.storyScenes.miraTrace.group.visible, true, 'the broken scout marker appears only during Mira stage two');
  assert.equal(world.interactables.find(item => item.id === 'mira_scout_trace').mesh.visible, true);
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: 'wind_release' }, defeated: ['grove_warden', 'marsh_warden', 'peak_warden'], npcFlags: { groveReport: false, marshReport: false, ilyaTruth: false } });
  assert.equal(world.storyScenes.mira.group.visible, true, 'aftermath scenes remain sequential when several choices are already complete');
  assert.equal(world.storyScenes.orin.group.visible, false);
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: 'wind_release' }, defeated: ['grove_warden', 'marsh_warden', 'peak_warden'], npcFlags: { groveReport: true, marshReport: false, ilyaTruth: false } });
  assert.equal(world.storyScenes.mira.group.visible, false);
  assert.equal(world.storyScenes.orin.group.visible, true);
  assert.equal(world.storyScenes.orin.wardChannel.visible, true);
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: '' }, defeated: ['grove_warden', 'marsh_warden'], characterQuests: { mira: 3, orin: 1, ilya: 0 }, npcFlags: { groveReport: true, marshReport: true } });
  assert.equal(world.storyScenes.orin.group.visible, false);
  assert.equal(world.storyScenes.orinFault.group.visible, true, 'the damaged sluice appears only during Orin repair stage');
  assert.equal(world.interactables.find(item => item.id === 'orin_sluice_fault').mesh.visible, true);
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: '' }, defeated: ['grove_warden', 'marsh_warden'], characterQuests: { mira: 3, orin: 3, ilya: 0 }, npcFlags: { groveReport: true, marshReport: true } });
  const wheelBefore = world.storyScenes.orinFault.wheel.rotation.z;
  world.update(3, new THREE.Vector3(-220, terrainHeight(-220, 350), 350));
  assert.equal(world.storyScenes.orinFault.group.visible, true, 'the repaired sluice remains as a persistent world consequence');
  assert.notEqual(world.storyScenes.orinFault.wheel.rotation.z, wheelBefore, 'the repaired wheel moves after completion');
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: 'wind_release' }, defeated: ['grove_warden', 'marsh_warden', 'peak_warden'], npcFlags: { groveReport: true, marshReport: true, ilyaTruth: false } });
  assert.equal(world.storyScenes.ilya.group.visible, true);
  const before = world.storyScenes.ilya.actor.userData.rig.halo.rotation.z;
  world.update(2, new THREE.Vector3(0, terrainHeight(0, -615), -615));
  assert.notEqual(world.storyScenes.ilya.actor.userData.rig.halo.rotation.z, before, 'Ilya has an articulated spectral idle animation');
  world.setNarrativeState({ choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: 'wind_release' }, defeated: ['grove_warden', 'marsh_warden', 'peak_warden'], characterQuests: { mira: 3, orin: 3, ilya: 1 }, npcFlags: { groveReport: true, marshReport: true, ilyaTruth: false } });
  assert.equal(world.storyScenes.ilya.group.visible, false);
  assert.equal(world.storyScenes.ilyaArchive.group.visible, true, 'Ilya archive appears only during the coast investigation');
  assert.equal(world.interactables.find(item => item.id === 'ilya_archive_echo').mesh.visible, true);
  world.setNarrativeState({ victory: true, choices: { grove: 'wild_bloom', marsh: 'water_ward', peak: 'wind_release' }, defeated: ['grove_warden', 'marsh_warden', 'peak_warden', 'crown_warden'], characterQuests: { mira: 3, orin: 3, ilya: 3 }, relationships: { mira: 3, orin: 3, ilya: 3 }, npcFlags: { groveReport: true, marshReport: true, ilyaTruth: true } });
  assert.equal(world.storyScenes.council.group.visible, true, 'the postgame council requires all three strongest relationships');
  world.dispose();
});
