#!/usr/bin/env python3
"""One-role source-aware LOD comparison for the authored Mira face.
Re-runs endpoint selection on the licensed deformed source; no subdivision.
"""
from pathlib import Path
import hashlib,json,runpy,time
import numpy as np
start=time.perf_counter();ROOT=Path(__file__).resolve().parents[2];ASSETS=ROOT/'src/assets/characters'
inputs=runpy.run_path(str(ROOT/'scripts/characters/generate-face-identities.py'))
weights=[1.1,.7,0];delta=sum(c*d for c,d in zip(weights,inputs['basis_d']))
reference=ROOT/'scripts/characters/generate-anatomical-head.py';source=reference.read_text()
source=source.replace("OUT=ROOT/'src/assets/characters/anatomical-head-data.js'","OUT=ROOT/'src/assets/characters/identity-head-data.js'").replace("PROVENANCE=ROOT/'src/assets/characters/anatomical-head-provenance.json'","PROVENANCE=ROOT/'src/assets/characters/identity-head-provenance.json'")
source=source.replace('faces={};fuvs={};','positions+=identity_delta\nfaces={};fuvs={};').replace('target=1500','target=1600')
source=source.replace('OUT.write_text(body)','identity_output_body=body').replace('OUT.stat().st_size','len(identity_output_body.encode())').replace('OUT.read_bytes()','identity_output_body.encode()').replace("PROVENANCE.write_text(","identity_provenance_sink(")
namespace={'__file__':str(reference),'identity_delta':delta,'identity_provenance_sink':lambda value:None};exec(compile(source,str(reference),'exec'),namespace)
out=ASSETS/'identity-head-data.js';body=namespace['identity_output_body'].replace('// Generated by scripts/characters/generate-anatomical-head.py.', '// Generated by scripts/characters/generate-identity-head.py.')
p=namespace['provenance'];p['asset']=out.name;p['origin']='Authored Mira face: official CC0 hm08 head-oval and nasal-width offsets registered with Q boundary protection, followed by source-aware endpoint LOD. No demographic inference or likeness.'
p['generator']='scripts/characters/generate-identity-head.py';p['generatorSha256']=hashlib.sha256(Path(__file__).read_bytes()).hexdigest();p['outputSha256']=hashlib.sha256(body.encode()).hexdigest();p['outputBytes']=len(body.encode())
p['registrationRecipe']={'file':'scripts/characters/generate-anatomical-head.py','sha256':hashlib.sha256(reference.read_bytes()).hexdigest()};p['morphRecipe']={'file':'scripts/characters/generate-face-identities.py','sha256':hashlib.sha256((ROOT/'scripts/characters/generate-face-identities.py').read_bytes()).hexdigest()};p['morphSources']=inputs['sources'];p['morphsApplied']=[{'source':s['file'],'coefficient':c}for s,c in zip(inputs['sources'],weights)if c];p['application']=inputs['provenance']['application'];p['application']['unchanged']='Original UV coordinates and all source seam corners, all existing bones, eye/lid/neck/clothing/material/motion contracts. Only npc uses this source-aware LOD.';p['application']['method']='Blend boundary-protected registered original target offsets on the full source BEFORE endpoint QEM; reselect vertices, retain original UV corners, and regenerate smooth source/LOD fallback normals. Runtime receives the compiled geometry, not basis-normal interpolation.';p['archivedUnappliedSources']=[s for s in p['archivedUnappliedSources'] if s['file'] not in [m['source'] for m in p['morphsApplied']]];p['role']='npc';p['passesSourceDistanceGate']=bool(p['lod']['sourceVertexDistanceM']['max']<.0075 and p['lod']['sourceVertexDistanceM']['p95']<.0021)
assert p['passesSourceDistanceGate'], 'Source-aware NPC LOD exceeds unchanged distance gates'
out.write_text(body)
(ASSETS/'identity-head-provenance.json').write_text(json.dumps(p,indent=2)+'\n')
print(json.dumps({'identitySeconds':time.perf_counter()-start,'head':p['lod'],'passesSourceDistanceGate':p['passesSourceDistanceGate'],'outputBytes':p['outputBytes']},indent=2))
