from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,subprocess,collections,math
ROOT=Path('/workspace/scratch/e72662e3b71f/Q-mira-micro-v62')
OUT=Path(__file__).resolve().parent
B='docs/evidence/mira-micro-v61/'
files=['AGENTS.md','docs/PROJECT_STATE.md','docs/MIRA_MICRO_PARTS_V61.md','docs/MIRA_MICRO_INTEGRATION_V62.md',B+'PART_INDEX.json',B+'planning/head/type-manifest.json',B+'planning/head/parts-draft.json',B+'planning/cloth/types.json',B+'planning/cloth/parts.json',B+'planning/cloth/PLAN.md',B+'planning/accessories/STAFF_MICRO_BOM.json',B+'planning/accessories/HANDS_BOOTS_MICRO_PLAN.json',B+'references/head/face-patches-manifest.json',B+'references/head/REVIEW.md','review/micro-v61/mira-micro-parts.js','review/lantern-micro-v62/mira-lantern-ribs.js','review/cloth-micro-v62/surfaces.mjs','docs/evidence/mira-cloth-micro-v62/meshes.json','docs/evidence/mira-micro-v62/independent/ribs-native-v62/result.json','docs/evidence/mira-micro-v62/independent/cloth-native-v62/native-check.json']
images=[B+'references/staff-caps-micro-v1.png','docs/evidence/mira-micro-v62/references/staff-ribs/staff-ribs-micro-v2.png',B+'references/cloth/mira-cloth-three-micro-parts-v2.png',B+'references/head/mira-face-patches-F01-F05-F09-v2.png','docs/evidence/character-reference-v60/references/mira-complete-six-views-v1.png','docs/evidence/character-reference-v60/references/mira-hands-staff-views-v1.png']
git=lambda *args:subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
ref='22d1d041dd6aef60de7764b1eebf6cf78028c857'
assert git('rev-parse','HEAD^{tree}')==git('rev-parse',ref+'^{tree}')=='837c6b5dd804a33746e3a1116254bc5202c7dd6d'
assert not git('status','--short')
sha=lambda data:hashlib.sha256(data).hexdigest()
manifest={'readAt':datetime.now(timezone.utc).isoformat(),'repository':str(ROOT),'requestedCommit':ref,'observedLocalHead':git('rev-parse','HEAD'),'tree':git('rev-parse','HEAD^{tree}'),'sameTree':True,'gitStatus':'','sources':[{'path':n,'bytes':len((ROOT/n).read_bytes()),'sha256':sha((ROOT/n).read_bytes()),'originalBitmapViewed':n in images} for n in files+images]}
load=lambda n:json.loads((ROOT/n).read_text())
idx=load(B+'PART_INDEX.json');head=load(B+'planning/head/parts-draft.json');cloth=load(B+'planning/cloth/types.json');staff=load(B+'planning/accessories/STAFF_MICRO_BOM.json');hands=load(B+'planning/accessories/HANDS_BOOTS_MICRO_PLAN.json');meshes=load('docs/evidence/mira-cloth-micro-v62/meshes.json')
scopes=collections.Counter(x['scope'] for x in idx['types']);assert sum(scopes.values())==103 and sum(idx['plannedInstances'].values())==250
keyCount=collections.Counter(x['key'] for x in idx['types']);assert max(keyCount.values())==1
local=collections.defaultdict(list)
for row in idx['types']:local[row['localId']].append(row['key'])
contracts=[]
for m in meshes:
 for edge,e in m['boundary'].items():
  pts=[m['positions'][i] for i in e['vertices']]
  contracts.append({'id':'cloth:'+m['id']+':'+edge,'part':'cloth:'+m['id'],'edge':edge,'targetConcept':e['neighbour'],'sourceVertexIndices':e['vertices'],'sampleCount':len(pts),'positionsMetres':pts,'controlsMetres':e['controls'],'boundsMillimetres':[[min(p[a] for p in pts)*1000,max(p[a] for p in pts)*1000] for a in range(3)],'sourceSkinWeights':[m['skinWeights'][i] for i in e['vertices']],'welded':e['weldedToNeighbour'],'uvContinuity':e['uvContinuityWithNeighbour'],'normalContinuity':e['normalContinuityWithNeighbour']})
pinside=next(e for e in contracts if e['id']=='cloth:P01-R:inside')
mirrorGaps=[abs(2*p[0])*1000 for p in pinside['positionsMetres']]
headNeeded=[p for p in head['parts'] if p['id'] in ['F01-L','F03-L','F05-L','F07-L','F09-L','N01','N02']]
existing=['staff:S09','staff:S10','staff:S11','staff:S12','staff:S13','staff:S14','cloth:T01-R','cloth:S05-R','cloth:P01-R']
coverage=[{'scope':'head','plannedTypes':30,'plannedInstances':62,'acceptedOrConditionalMicroReferenceIds':['F01-L','F05-L','F09-L'],'fabricatedCandidateFormCount':0,'fabricatedCandidateInstances':0,'status':'reference shapes only; metric/weld boundaries unresolved'}, {'scope':'cloth','plannedTypes':34,'plannedInstances':79,'acceptedOrConditionalMicroReferenceIds':['T01-R','S05-R','P01-R'],'fabricatedCandidateFormCount':3,'fabricatedCandidateInstances':3,'status':'isolated open surfaces; no neighboring seams assembled; P01 old support penetrates floor'}, {'scope':'hands-boots','plannedTypes':21,'plannedInstances':90,'acceptedOrConditionalMicroReferenceIds':[],'fabricatedCandidateFormCount':0,'fabricatedCandidateInstances':0,'status':'plan/coarse reference only'}, {'scope':'staff','plannedTypes':18,'plannedInstances':19,'acceptedOrConditionalMicroReferenceIds':['S13','S14','wide:S09/S10','depth:S11/S12'],'fabricatedCandidateFormCount':4,'fabricatedCandidateInstances':6,'status':'caps2 + ribs2 shared forms /6 placements; lower seats/glow/finial/staff/hand unresolved'}]
interfaces=[
 {'id':'staff:lower-rib-seat','members':['staff:S09','staff:S10','staff:S11','staff:S12','staff:S08'],'status':'source endpoint fixed; receiver missing','frame':'staff mm, Y up, shaft bottom Y0','datumYmm':1447,'axis':[0,1,0],'ribEndPad':{'centerRadiusMm':16.75,'radialBoundsMm':[15.25,18.25],'tangentialBoundsMm':[-4,4],'chamferMm':.2,'areaMm2':23.919997708797375},'receiverConstraint':'S08 upward planar seat at Y1447 must contain all four native end pads; select angular phase and test polygon faces, not circumscribed radii alone. Existing S13-style ring r14.5..19.2 with same16 phase is one already supported shape, not mandatory S08 source.','unknown':['S08 complete radial profile','S08 underside seat Y/profile toward S07']},
 {'id':'staff:upper-rib-seat','members':['staff:S09','staff:S10','staff:S11','staff:S12','staff:S13'],'status':'fixed partial native contact','datumYmm':1662,'sourceEvidence':'v62 ribs-native result.json; no new native sweep this unit'},
 {'id':'staff:cap-seat','members':['staff:S13','staff:S14'],'status':'fixed partial native contact','datumYmm':1668,'capSegments':16,'sourceEvidence':'caps-budget-v1 + v62 native frozen profile'},
 {'id':'staff:cup-ring-glow','members':['staff:S06','staff:S07','staff:S08','staff:S16'],'status':'missing surfaces; old BOM dimensions provisional','knownDraft':{'S06Ymm':[1394,1432],'S07Ymm':[1427,1448],'glowLowerPoleYmm':1447},'requiredDistinctSurfaceOwnership':['S07 underside to S06 socket','S07 annular or named receiver to S08 underside','S07 internal lower-glow seat to S16','S08 upward receiver for four ribs'],'unknown':['final S07 profile','seat normals and contact area to S08','S16 actual lower closure/contact shape','S06 actual mating mesh']},
 {'id':'staff:glow-envelope','members':['staff:S16','staff:S14','staff:S07','staff:S09','staff:S10','staff:S11','staff:S12'],'status':'not globally clear; old S14 envelope defect unresolved','centerMm':[0,1556,0],'radiiMm':[52,109,39],'axes':'staff X/Y/Z','S14normalizedRadius16':.9994088571055387,'S14normalizedRadius24':.9997378781391432,'required':'Keep one S16 owner. Declare actual pole truncation/socket surfaces and measure actual triangles separately from ellipsoid envelope. Preserve gross dimensions unless explicitly reviewed. Do not equate normalized deficit to mm penetration or hidden overlap to clear.'},
 {'id':'cloth:P01-support','members':['cloth:P01-R','cloth:P04-R','rig:chest'],'status':'top9 registration fixed; deformation candidate currently outside this audited tree','topIndices':next(c['sourceVertexIndices'] for c in contracts if c['id']=='cloth:P01-R:top'),'frame':'chest-bind metres; rootOffset [0,.985,0]','constraint':'Existing top positions, source weights, ordered edge and time/state transform remain exact; P04 eventual shared edge must read the same boundary solution, not independently simulated approximate points.','unknown':['P04 actual edge','skin-to-cloth support/contact thickness','body collision beyond requested local floor support']},
 {'id':'cloth:P01-centre','members':['cloth:P01-R','cloth:P01-L','cloth:REAR-CENTRE'],'status':'unjoined conceptual alternative; choose one explicit owner before full cape assembly','mirrorGapMm':[min(mirrorGaps),max(mirrorGaps)],'constraint':'R inside x=-.005 m. Mirroring gives L x=+.005 m, so these are not a welded center. Register one shared seam or define an owned connector with an ID; do not count either as already made.','unknown':['seam versus connector decision','left actual geometry','shared runtime support solution']},
 {'id':'head:three-patch-boundaries','members':['head:F01-L','head:F05-L','head:F09-L','head:F03-L','head:F07-L'],'status':'conceptual only; no metric boundary vertices','constraint':'Use single open skin surfaces; no cast backing/beveled inner rim from reference picture. F05 to F09 requires missing F07. F01 lists F05 but reciprocal endpoint/edge is absent: reconcile named adjacency before welding. Define shared ordered positions/tangents/normals/skin weights in head-local frame once.','guideEnvelopeMm':{'F01-L':[55,55,25],'F05-L':[40,35,40],'F09-L':[38,35,45]},'guideIsCalibrated':False,'unknown':['scale registration to fixed head landmarks','boundary curves/vertex IDs','exact reciprocal neighboring edges','UV charts and deformed seam policy']},
 {'id':'head:neck-cloth','members':['head:N01','head:N02','cloth:C01','cloth:C02','rig:neck'],'status':'historical registration reference; not joined new micro assembly','constraint':'Head owns neck cut and skin; costume owns stand collar/cowl/brooch. Existing 46-point neck rim is a source reuse candidate only after exact point/weight/frame correspondence. Do not import stale coarse212-grid +X-right data as current geometry.'}
]
result={'capturedAt':manifest['readAt'],'source':{k:manifest[k] for k in ['repository','requestedCommit','observedLocalHead','tree','sameTree']},'plannedCoverage':coverage,'plannedTypeSlotsTotal':103,'plannedPlacementsTotal':250,'fabricatedCandidateUniqueForms':7,'fabricatedCandidatePlacements':9,'fabricatedCandidateIds':existing,'historicalIndexFabricatedIds':idx['candidateFabricatedIds'],'allImagesFixed':False,'completeCharacter':False,'runtimeAdopted':False,'localIdCollisionsRequireNamespace':{k:v for k,v in local.items() if len(v)>1},'P01MirroredInsideGapMm':[min(mirrorGaps),max(mirrorGaps)],'clothBoundaryContracts':contracts,'headPriorityPlan':headNeeded,'frameContract':{'character':'anatomical R=-X/L=+X/front=+Z','staff':'millimetres, model shaft bottom y0; staff-to-hand transform not registered by this unit','cloth':'chest bind metres; root offset (0,.985,0); bone0 is anatomicalR','head':'head-local; left patch +X; no common metric patch boundary yet'},'excludedStalePlan':{'path':B+'planning/cloth/parts.json','reason':'212 uniform-grid draft retains obsolete +X-right convention; use types.json/PLAN.md and actual v62 surfaces, not this retained draft'},'limits':['No generated image is calibrated CAD or proof of same 3D identity','No source edits/new geometry/new image/renderer/remote actions','Current v63 work in other worktrees is not included in accepted coverage','No quality percentage/whole actor draw or device/PS4 acceptance']}
(OUT/'SOURCE_HASHES.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
(OUT/'audit.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
(OUT/'interfaces.json').write_text(json.dumps({'interfaces':interfaces},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'source':result['source'],'coverage':coverage,'P01MirrorGapMm':result['P01MirroredInsideGapMm'],'sourceFiles':len(manifest['sources']),'interfaces':len(interfaces)},ensure_ascii=False,indent=2))
