(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.ScriptOverlapCore = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const STOP = new Set(['これ','それ','ため','よう','こと','もの','です','ます','いる','ある','する','した','して','から','まで','より','そして','しかし','the','and','that','this','with','from','your','you','are','for','not']);
  function stripSubtitleNoise(text) { return String(text || '').replace(/^WEBVTT.*$/gmi, ' ').replace(/^\s*\d+\s*$/gm, ' ').replace(/^\s*\d{1,2}:\d{2}(?::\d{2})?[,.]\d{3}\s*-->\s*\d{1,2}:\d{2}(?::\d{2})?[,.]\d{3}.*$/gm, ' ').replace(/<[^>]+>/g, ' ').replace(/\[[^\]]{0,40}\]/g, ' ').replace(/^#{1,6}\s+/gm, '').replace(/[*_`>|]/g, ' '); }
  function normalize(text) { return stripSubtitleNoise(text).normalize('NFKC').toLowerCase().replace(/https?:\/\/\S+/g, ' ').replace(/[\u200b-\u200d\ufeff]/g, '').replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim(); }
  function compact(text) { return normalize(text).replace(/[\s\p{P}\p{S}]+/gu, ''); }
  function splitSentences(text) { const cleaned = normalize(text).replace(/([。！？!?])\s*/g, '$1\n').replace(/\n+/g, '\n'); return cleaned.split('\n').map(s => s.trim()).filter(s => compact(s).length >= 8); }
  function charNgrams(text, n) { const s = compact(text), out=[]; for(let i=0;i<=s.length-n;i++) out.push(s.slice(i,i+n)); return out; }
  function wordTokens(text) { const s=normalize(text); const latin=s.match(/[a-z0-9]+(?:['’-][a-z0-9]+)?/g)||[]; const chunks=s.match(/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}ー]{2,}/gu)||[]; const jp=[]; for(const c of chunks){ if(c.length<=4) jp.push(c); else for(let i=0;i<=c.length-3;i++) jp.push(c.slice(i,i+3)); } return latin.concat(jp).filter(t=>!STOP.has(t)); }
  function frequency(items){const m=new Map();for(const x of items)m.set(x,(m.get(x)||0)+1);return m;}
  function cosine(a,b){const A=frequency(a),B=frequency(b);let dot=0,aa=0,bb=0;for(const v of A.values())aa+=v*v;for(const v of B.values())bb+=v*v;for(const [k,v] of A)dot+=v*(B.get(k)||0);return aa&&bb?dot/Math.sqrt(aa*bb):0;}
  function jaccard(a,b){const A=new Set(a),B=new Set(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/(A.size+B.size-n);}
  function structure(text){const paragraphs=normalize(text).split(/\n\s*\n/).filter(Boolean), sentences=splitSentences(text), lengths=sentences.map(s=>compact(s).length), avg=lengths.length?lengths.reduce((a,b)=>a+b,0)/lengths.length:0, buckets=[0,0,0,0];for(const n of lengths)buckets[n<25?0:n<50?1:n<90?2:3]++;const total=Math.max(1,lengths.length);return{paragraphs:paragraphs.length,sentences:sentences.length,avg,buckets:buckets.map(v=>v/total)};}
  function structureSimilarity(a,b){const ratio=(x,y)=>(x||y)?Math.min(x,y)/Math.max(x,y):1;const hist=1-a.buckets.reduce((s,v,i)=>s+Math.abs(v-b.buckets[i]),0)/2;return Math.max(0,Math.min(1,.25*ratio(a.paragraphs,b.paragraphs)+.25*ratio(a.sentences,b.sentences)+.2*ratio(a.avg,b.avg)+.3*hist));}
  function edges(s){return{intro:s.slice(0,3).join(' '),outro:s.slice(-3).join(' ')}};
  function pairScore(a,b){const ng=cosine(charNgrams(a.text,4),charNgrams(b.text,4)),tok=jaccard(wordTokens(a.text),wordTokens(b.text)),st=structureSimilarity(a.structure,b.structure),intro=cosine(charNgrams(a.edges.intro,3),charNgrams(b.edges.intro,3)),outro=cosine(charNgrams(a.edges.outro,3),charNgrams(b.edges.outro,3));return{score:Math.min(1,.46*ng+.22*tok+.16*st+.09*intro+.07*outro),ngramSimilarity:ng,tokenSimilarity:tok,structureSimilarity:st,introSimilarity:intro,outroSimilarity:outro};}
  function riskBand(score,medium=.42,high=.68){return score>=high?'high':score>=medium?'medium':'low';}
  function repeatedSegments(docs){const exact=new Map();docs.forEach((d,di)=>{const seen=new Set();d.sentences.forEach((s,si)=>{const k=compact(s);if(k.length<18||seen.has(k))return;seen.add(k);if(!exact.has(k))exact.set(k,{text:s,docs:new Set(),hits:[]});exact.get(k).docs.add(di);exact.get(k).hits.push({doc:di,sentence:si});});});const rows=[...exact.values()].filter(x=>x.docs.size>=2).map(x=>({type:'exact',text:x.text,documentCount:x.docs.size,documents:[...x.docs],hits:x.hits,score:1}));const ss=[];docs.forEach((d,di)=>d.sentences.forEach((s,si)=>{if(compact(s).length>=24)ss.push({di,si,text:s,grams:charNgrams(s,3)});}));const near=[];for(let i=0;i<ss.length;i++)for(let j=i+1;j<ss.length;j++){const a=ss[i],b=ss[j];if(a.di===b.di)continue;const sim=cosine(a.grams,b.grams);if(sim>=.78&&compact(a.text)!==compact(b.text))near.push({type:'near',text:a.text,otherText:b.text,documentCount:2,documents:[a.di,b.di],score:sim});}near.sort((a,b)=>b.score-a.score);return rows.concat(near.slice(0,40)).sort((a,b)=>b.score-a.score||b.documentCount-a.documentCount).slice(0,80);}
  function diversity(text){const t=wordTokens(text);return t.length?new Set(t).size/t.length:0;}
  function analyze(inputDocs,options={}){const medium=Number(options.mediumThreshold??.42),high=Number(options.highThreshold??.68);const docs=inputDocs.map((d,i)=>{const text=normalize(d.text),sentences=splitSentences(text);return{id:d.id||String(i+1),name:d.name||`台本${i+1}`,text,characters:compact(text).length,sentences,structure:structure(text),edges:edges(sentences),diversity:diversity(text)};}).filter(d=>d.characters>=20);const pairs=[];for(let i=0;i<docs.length;i++)for(let j=i+1;j<docs.length;j++){const m=pairScore(docs[i],docs[j]);pairs.push({a:i,b:j,aName:docs[i].name,bName:docs[j].name,...m,risk:riskBand(m.score,medium,high)});}pairs.sort((a,b)=>b.score-a.score);const repeated=repeatedSegments(docs),priorities=[];for(const p of pairs.filter(x=>x.risk!=='low').slice(0,12)){const r=[];if(p.introSimilarity>=.7)r.push('冒頭が同型');if(p.outroSimilarity>=.7)r.push('締めが同型');if(p.structureSimilarity>=.82)r.push('構成が同型');if(p.ngramSimilarity>=.62)r.push('本文の言い回しが近い');priorities.push({severity:p.risk,documents:[p.aName,p.bName],score:p.score,action:(r.length?r.join('・'):'共通句が多い')+'。具体例、順序、導入または結論を差し替える。'});}repeated.slice(0,12).forEach(r=>priorities.push({severity:r.type==='exact'?'high':'medium',documents:r.documents.map(i=>docs[i].name),score:r.score,action:`反復箇所「${(r.text||'').slice(0,80)}」を動画固有の説明へ置き換える。`}));const avg=pairs.length?pairs.reduce((s,p)=>s+p.score,0)/pairs.length:0,max=pairs.length?pairs[0].score:0;return{generatedAt:new Date().toISOString(),documentCount:docs.length,docs,pairs,repeatedSegments:repeated,priorities:priorities.slice(0,30),summary:{averageSimilarity:avg,maximumSimilarity:max,highPairs:pairs.filter(p=>p.risk==='high').length,mediumPairs:pairs.filter(p=>p.risk==='medium').length,exactRepeated:repeated.filter(r=>r.type==='exact').length,risk:riskBand(max,medium,high)},thresholds:{medium,high},disclaimer:'類似度のヒューリスティック監査です。YouTubeの審査、著作権侵害、収益化可否を判定または保証しません。'};}
  return{normalize,stripSubtitleNoise,splitSentences,charNgrams,wordTokens,cosine,jaccard,analyze,riskBand};
});
