import{globSync,readFileSync,statSync}from'node:fs';import{spawnSync}from'node:child_process';
const required=['index.html','styles.css','manifest.webmanifest','icon.svg','sw.js','src/main.js','src/game.js','src/core.js','src/storage.js','src/audio.js','assets-manifest.json','PROJECT_OPERATING_PROTOCOL.md','AI_DEVELOPMENT/STATE.yaml','AI_DEVELOPMENT/PLAN.yaml','AI_DEVELOPMENT/ACCEPTANCE.yaml'],fails=[];for(const f of required)try{if(!statSync(f).isFile())fails.push(`${f} not file`)}catch{fails.push(`missing ${f}`)}
if(process.env.FLOOR_TEST_BAD==='F3')fails.push('DELIBERATE F3 FAILURE OBSERVED');
const html=readFileSync('index.html','utf8');if(/(?:src|href)=["']\/(?!\/)/.test(html))fails.push('root-relative path in index');if(!html.includes('user-scalable=no'))fails.push('viewport zoom policy missing');
try{const m=JSON.parse(readFileSync('manifest.webmanifest'));if(m.start_url!=='./'||m.scope!=='./')fails.push('manifest paths not relative')}catch(e){fails.push(`manifest ${e.message}`)}try{const a=JSON.parse(readFileSync('assets-manifest.json'));if(a.externalRuntimeAssets?.length)fails.push('external runtime asset declared')}catch(e){fails.push(`assets ${e.message}`)}
for(const f of ['index.html','styles.css','sw.js',...globSync('src/*.js')]){const t=readFileSync(f,'utf8'),urls=[...t.matchAll(/https?:\/\/[^\s"')]+/g)].map(x=>x[0]).filter(x=>!x.startsWith('http://www.w3.org/2000/svg'));if(urls.length)fails.push(`external URL ${f}`)}
for(const f of ['sw.js',...globSync('src/*.js'),...globSync('tools/*.mjs'),...globSync('tests/*.mjs')]){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status)fails.push(`syntax ${f}: ${r.stderr.trim()}`)}
const release=['index.html','styles.css','manifest.webmanifest','icon.svg','sw.js',...globSync('src/*.js')],total=release.reduce((n,f)=>n+statSync(f).size,0),code=['styles.css',...globSync('src/*.js')].reduce((n,f)=>n+statSync(f).size,0);if(total>1500000)fails.push(`payload ${total}`);if(code>250000)fails.push(`code ${code}`);for(const f of ['index.html','styles.css','icon.svg','manifest.webmanifest','src/main.js','src/game.js','src/core.js','src/storage.js','src/audio.js'])if(!readFileSync('sw.js','utf8').includes(`./${f}`))fails.push(`cache missing ${f}`);
if(fails.length){for(const f of fails)console.error('FAIL',f);process.exit(1)}console.log(`Validation passed: ${required.length} required files, ${total} release bytes, ${code} JS+CSS bytes, no external runtime URLs.`);
