// Original procedural sound. Audio starts only after a player gesture.
export class Soundscape {
  constructor(){this.ctx=null;this.volume=.45;this.music=true;this.nextNote=0;this.note=0;this.nodes=[];}
  start(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=this.volume;this.master.connect(this.ctx.destination);this.wind=this.ctx.createGain();this.wind.gain.value=.065;this.wind.connect(this.master);const b=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate);const a=b.getChannelData(0);let v=0;for(let i=0;i<a.length;i++){v=(v+Math.random()*.04-.02)*.985;a[i]=v;}const n=this.ctx.createBufferSource();n.buffer=b;n.loop=true;const f=this.ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=450;n.connect(f);f.connect(this.wind);n.start();this.nodes.push(n);}
    this.ctx.resume().catch(()=>{});
  }
  setVolume(v){this.volume=v;if(this.master)this.master.gain.setTargetAtTime(v,this.ctx.currentTime,.08);}
  tone(freq,duration=.2,volume=.1,type='sine',end=null,delay=0){if(!this.ctx)return;const c=this.ctx,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(end,1),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(volume,.0002),t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.03);o.onended=()=>{o.disconnect();g.disconnect();};}
  noise(duration,volume,cutoff){if(!this.ctx)return;const c=this.ctx,b=c.createBuffer(1,Math.max(1,c.sampleRate*duration|0),c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(1-i/a.length);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=cutoff;g.gain.value=volume;s.connect(f);f.connect(g);g.connect(this.master);s.start();s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
  play(type){if(type==='bowDraw')this.tone(180,.75,.03,'triangle',280);if(type==='arrow')this.noise(.18,.12,2600);if(type==='arrowBreak')this.noise(.09,.1,1800);if(type==='swing'){this.noise(.2,.25,1700);this.tone(240,.14,.06,'triangle',70);}if(type==='hit'){this.noise(.15,.45,3000);this.tone(95,.16,.2,'triangle',40);}if(type==='hurt'){this.noise(.18,.24,600);this.tone(75,.3,.18,'sine',34);}if(type==='dodge')this.noise(.25,.12,700);if(type==='perfect'){this.tone(1100,.45,.16,'sine');this.tone(1650,.55,.09,'sine');}if(['heal','skill','beacon','level','rest','loot'].includes(type)){for(let i=0;i<4;i++)this.tone([293.66,440,587.33,880][i],.8,.08,'sine',null,i*.09);}if(type==='death'){this.tone(98,2,.12,'triangle',45);this.tone(146,2,.08,'sine',60);}if(type==='enemySwing')this.noise(.2,.2,600);}
  tick(t,combat=false){if(!this.ctx||!this.music||this.ctx.state!=='running')return;if(t<this.nextNote)return;this.nextNote=t+(combat?1.1:2.7);const scale=[146.83,220,293.66,329.63,220,196,293.66,440];const n=scale[this.note++%scale.length];this.tone(combat?n*.5:n,3,.022,'sine');this.tone(n*2,2,.009,'sine',null,.13);if(this.note%7===0&&!combat){this.tone(1800,.18,.022,'sine',2600,.45);this.tone(2400,.18,.012,'sine',1800,.7);}}
  suspend(){if(this.ctx)this.ctx.suspend().catch(()=>{});}
}
