import{beamHits,clamp,distance,formatNumber,lerp,rng,upgradeChoices}from'./core.js';
const TAU=Math.PI*2,STEP=1/60;
const ENEMIES={seeker:{hp:42,speed:47,r:12,score:100,color:'#ff557d'},gunner:{hp:36,speed:32,r:12,score:140,color:'#ff9b68'},charger:{hp:68,speed:36,r:14,score:190,color:'#ffd36f'},splitter:{hp:58,speed:38,r:15,score:220,color:'#c879ff'},mite:{hp:18,speed:69,r:8,score:50,color:'#e8a0ff'},node:{hp:95,speed:0,r:13,score:280,color:'#7fa8ff'}};
const BOSSES=[{name:'GYRE KEEPER',hp:900,r:36,color:'#ef68ff'},{name:'DEAD STAR',hp:2100,r:47,color:'#ffb966'}];
const callbacks={hud(){},status(){},upgrade(){},result(){},toast(){},quality(){}};
const pct=(arr,p)=>{if(!arr.length)return 0;const s=[...arr].sort((a,b)=>a-b);return s[Math.min(s.length-1,Math.floor(s.length*p))]};
const polygon=(ctx,n,r,rot=0)=>{ctx.beginPath();for(let i=0;i<n;i++){const a=rot+i/n*TAU,x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath()};

export class Game{
 constructor(canvas,{sound,callbacks:cb={}}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});this.sound=sound;this.cb={...callbacks,...cb};this.w=375;this.h=667;this.dpr=1;this.quality=2;this.state=null;this.random=rng(1);this.pointer=null;this.anchor=null;this.acc=0;this.last=performance.now();this.samples=[];this.hudTimer=0;this.shake=0;this.flash=0;this.soundTimer=0;this.loop=this.loop.bind(this);this.bind();this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(canvas.parentElement);this.resize();requestAnimationFrame(this.loop)}
 bounds(){return{left:18,right:this.w-18,top:this.h<620?63:75,bottom:this.h-(this.h<620?58:72)}}
 newState(seed){const b=this.bounds();return{status:'running',seed,clock:0,wave:1,score:0,hp:3,maxHp:3,invuln:0,energy:100,maxEnergy:100,combo:0,maxCombo:0,comboTime:0,levels:{},shield:0,leech:0,player:{x:(b.left+b.right)/2,y:b.bottom-90,vx:105,vy:-62,radius:9},enemies:[],bullets:[],particles:[],rings:[],floaters:[],trail:[],stars:[],spawnLeft:0,spawnTimer:0,waveIntro:0,waveStarted:false,clearTime:0,id:1,kills:0,cuts:0,metrics:{enemies:0,bullets:0,particles:0}}}
 start({seed=Date.now()}={}){this.random=rng(seed);this.state=this.newState(this.random.state);for(let i=0;i<70;i++)this.state.stars.push({x:this.random.next()*this.w,y:this.random.next()*this.h,a:.1+this.random.next()*.5,s:.4+this.random.next()*1.2,p:this.random.next()*TAU});this.pointer=null;this.anchor=null;this.acc=0;this.beginWave();this.sound?.start();this.cb.status('running')}
 stop(){this.pointer=null;this.anchor=null;if(this.state)this.state.status='idle';this.sound?.stop();this.cb.status('idle')}
 pause(reason='manual'){if(this.state?.status!=='running')return false;this.pointer=null;this.anchor=null;this.state.status='paused';this.state.pauseReason=reason;this.cb.status('paused',reason);return true}
 resume(){if(this.state?.status!=='paused')return false;this.state.status='running';this.last=performance.now();this.acc=0;this.cb.status('running');return true}
 bind(){const opts={passive:false};this.canvas.addEventListener('pointerdown',e=>{if(this.state?.status!=='running'||this.pointer!==null)return;e.preventDefault();this.sound?.unlock();this.pointer=e.pointerId;try{this.canvas.setPointerCapture(e.pointerId)}catch{}this.setAnchor(e);this.sound?.event('tether',.6)},opts);this.canvas.addEventListener('pointermove',e=>{if(e.pointerId!==this.pointer)return;e.preventDefault();this.setAnchor(e)},opts);const release=e=>{if(e.pointerId!==this.pointer)return;e.preventDefault();try{this.canvas.releasePointerCapture(e.pointerId)}catch{}this.pointer=null;this.anchor=null};this.canvas.addEventListener('pointerup',release,opts);this.canvas.addEventListener('pointercancel',release,opts);this.canvas.addEventListener('contextmenu',e=>e.preventDefault())}
 setAnchor(e){const r=this.canvas.getBoundingClientRect(),b=this.bounds();this.anchor={x:clamp(e.clientX-r.left,b.left,b.right),y:clamp(e.clientY-r.top,b.top,b.bottom)}}
 beginWave(){const s=this.state;s.waveStarted=false;s.waveIntro=1.2;s.clearTime=0;s.spawnLeft=0;s.spawnTimer=.45;s.enemies.length=0;s.bullets.length=0;s.shield=s.levels.shield?1:0;this.cb.toast(s.wave===4||s.wave===8?`RIFT ${s.wave} // ANOMALY`:`RIFT ${String(s.wave).padStart(2,'0')}`);this.sound?.event(s.wave===4||s.wave===8?'boss':'wave',.9)}
 activateWave(){const s=this.state;s.waveStarted=true;if(s.wave===4)this.spawnBoss(1);else if(s.wave===8)this.spawnBoss(2);else s.spawnLeft=Math.min(20,5+s.wave*2)}
 choices(){const s=this.state;if(s.status!=='upgrading')return[];return s.pending||[]}
 choose(id){const s=this.state;if(!s||s.status!=='upgrading')return false;const item=s.pending?.find(x=>x.id===id);if(!item)return false;s.levels[id]=(s.levels[id]||0)+1;if(id==='hull'){s.maxHp++;s.hp=s.maxHp}if(id==='energy'){s.maxEnergy+=25;s.energy=s.maxEnergy}s.pending=null;s.wave++;s.status='running';s.energy=Math.max(s.energy,s.maxEnergy*.58);this.sound?.event('upgrade');this.cb.status('running');this.beginWave();return true}
 rangeSpawn(r=16){const b=this.bounds(),side=this.random.int(0,3);if(side===0)return{x:b.left+r,y:lerp(b.top,b.bottom,this.random.next())};if(side===1)return{x:b.right-r,y:lerp(b.top,b.bottom,this.random.next())};if(side===2)return{x:lerp(b.left,b.right,this.random.next()),y:b.top+r};return{x:lerp(b.left,b.right,this.random.next()),y:b.bottom-r}}
 types(){const w=this.state.wave,out=['seeker'];if(w>=2)out.push('gunner');if(w>=3)out.push('charger');if(w>=5)out.push('splitter');return out}
 spawn(type=this.random.pick(this.types()),extra={}){const s=this.state,data=ENEMIES[type];if(!data||s.enemies.length>=34)return null;const p=extra.x==null?this.rangeSpawn(data.r):extra,scale=1+(s.wave-1)*.07,e={id:s.id++,type,x:p.x,y:p.y,vx:0,vy:0,radius:data.r*(extra.child?.82:1),hp:data.hp*scale*(extra.child?.7:1),maxHp:data.hp*scale*(extra.child?.7:1),speed:data.speed*(1+Math.min(.3,s.wave*.018)),score:data.score,color:data.color,age:0,shoot:.7+this.random.next()*1.3,ai:.6+this.random.next(),mode:'idle',rot:this.random.next()*TAU,flash:0,spark:0,child:Boolean(extra.child),parent:extra.parent,slot:extra.slot};s.enemies.push(e);this.particles(e.x,e.y,e.color,6,45);return e}
 spawnBoss(tier){const s=this.state,d=BOSSES[tier-1],b=this.bounds(),boss={id:s.id++,type:'boss',boss:true,tier,name:d.name,x:(b.left+b.right)/2,y:b.top+105,vx:0,vy:0,radius:d.r,hp:d.hp,maxHp:d.hp,speed:25+tier*4,score:4200*tier,color:d.color,age:0,shoot:1.2,summon:4.8,rot:0,flash:0,phase:1,nodes:0,secondNodes:false};s.enemies.push(boss);s.boss=boss;this.spawnNodes(boss,tier===1?3:4);s.rings.push({x:boss.x,y:boss.y,r:8,max:135,life:1,color:d.color})}
 spawnNodes(boss,count){boss.nodes+=count;for(let i=0;i<count;i++)this.spawn('node',{x:boss.x,y:boss.y,parent:boss.id,slot:i/boss.nodes*TAU})}
 bullet(x,y,a,speed=120,color='#ff688c',r=4.5){const s=this.state;if(s.bullets.length>=170)return;s.bullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,radius:r,color,life:7,age:0,dead:false})}
 aimed(e,count=1,spread=.15,speed=125){const a=Math.atan2(this.state.player.y-e.y,this.state.player.x-e.x);for(let i=0;i<count;i++)this.bullet(e.x,e.y,a+(i-(count-1)/2)*spread,speed,e.color)}
 radial(e,count,speed,offset=0){for(let i=0;i<count;i++)this.bullet(e.x,e.y,offset+i/count*TAU,speed,e.color)}
 gravity(){return 410*(1+(this.state.levels.gravity||0)*.22)}
 speedCap(){return 255*(1+(this.state.levels.velocity||0)*.2)}
 beamDamage(){const s=this.state,p=s.player,speed=Math.hypot(p.vx,p.vy),velocity=1+Math.min(1.3,speed/250)*(.65+(s.levels.velocity||0)*.1);return 44*(1+(s.levels.edge||0)*.35)*velocity}
 update(dt){const s=this.state;if(!s||s.status!=='running')return;s.clock+=dt;this.soundTimer=Math.max(0,this.soundTimer-dt);this.shake=Math.max(0,this.shake-dt*28);this.flash=Math.max(0,this.flash-dt*1.8);s.invuln=Math.max(0,s.invuln-dt);s.comboTime=Math.max(0,s.comboTime-dt);if(!s.comboTime)s.combo=0;
   if(this.anchor&&s.energy>0){const p=s.player,dx=this.anchor.x-p.x,dy=this.anchor.y-p.y,d=Math.hypot(dx,dy)||1,g=this.gravity();p.vx+=dx/d*g*dt;p.vy+=dy/d*g*dt;s.energy=Math.max(0,s.energy-dt*8.5);if(!s.energy){this.anchor=null;this.pointer=null;this.cb.toast('TETHER EMPTY')}}else{s.energy=Math.min(s.maxEnergy,s.energy+dt*19*(1+(s.levels.regen||0)*.3))}
   const p=s.player,max=this.speedCap(),spd=Math.hypot(p.vx,p.vy);if(spd>max){p.vx=p.vx/spd*max;p.vy=p.vy/spd*max}const drag=Math.pow(.992,dt*60);p.vx*=drag;p.vy*=drag;p.x+=p.vx*dt;p.y+=p.vy*dt;const b=this.bounds();if(p.x<b.left){p.x=b.left;p.vx=Math.abs(p.vx)*.78;this.wallSpark(p)}if(p.x>b.right){p.x=b.right;p.vx=-Math.abs(p.vx)*.78;this.wallSpark(p)}if(p.y<b.top){p.y=b.top;p.vy=Math.abs(p.vy)*.78;this.wallSpark(p)}if(p.y>b.bottom){p.y=b.bottom;p.vy=-Math.abs(p.vy)*.78;this.wallSpark(p)}s.trail.unshift({x:p.x,y:p.y});if(s.trail.length>(this.quality===2?42:24))s.trail.pop();
   if(s.waveIntro>0){s.waveIntro-=dt;if(s.waveIntro<=0)this.activateWave()}else{if(s.spawnLeft>0){s.spawnTimer-=dt;if(s.spawnTimer<=0){this.spawn();s.spawnLeft--;s.spawnTimer=Math.max(.43,.98-s.wave*.035)*(.7+this.random.next()*.6)}}for(const e of s.enemies)if(!e.dead)this.updateEnemy(e,dt);this.updateBullets(dt);this.updateBeam(dt);if(s.waveStarted&&!s.spawnLeft&&!s.enemies.some(e=>!e.dead)){s.clearTime+=dt;if(s.clearTime>.75)this.waveClear()}else s.clearTime=0}
   for(const q of s.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=Math.pow(.04,dt);q.vy*=Math.pow(.04,dt)}s.particles=s.particles.filter(q=>q.life>0);for(const r of s.rings){r.life-=dt;r.r=lerp(r.r,r.max,Math.min(1,dt*9))}s.rings=s.rings.filter(r=>r.life>0);for(const f of s.floaters){f.life-=dt;f.y-=23*dt}s.floaters=s.floaters.filter(f=>f.life>0);s.enemies=s.enemies.filter(e=>!e.dead);s.bullets=s.bullets.filter(x=>!x.dead&&x.life>0);s.metrics.enemies=Math.max(s.metrics.enemies,s.enemies.length);s.metrics.bullets=Math.max(s.metrics.bullets,s.bullets.length);s.metrics.particles=Math.max(s.metrics.particles,s.particles.length)}
 wallSpark(p){this.particles(p.x,p.y,'#75fff0',3,55)}
 updateBeam(dt){const s=this.state;if(!this.anchor)return;const p=s.player,width=5+(s.levels.width||0)*2.2;let hits=0;for(const e of s.enemies){if(e.dead||!beamHits(p,this.anchor,e,width))continue;if(e.boss&&e.nodes>0)continue;let damage=this.beamDamage();if(s.levels.focus&&distance(e,this.anchor)<74)damage*=2;this.damage(e,damage*dt,'beam');e.spark-=dt;if(e.spark<=0){this.particles(e.x,e.y,'#dffffb',2,35);e.spark=.09}hits++}for(const shot of s.bullets){if(!shot.dead&&beamHits(p,this.anchor,shot,width+2)){shot.dead=true;s.cuts++;s.score+=9;s.energy=Math.min(s.maxEnergy,s.energy+2.2);this.particles(shot.x,shot.y,'#8ffff4',2,48)}}if(hits&&this.soundTimer<=0){this.sound.event('cut',clamp(hits/3,.3,1));this.soundTimer=.11}}
 updateEnemy(e,dt){const s=this.state,p=s.player;e.age+=dt;e.rot+=dt*(e.boss?.55:1.2);e.flash=Math.max(0,e.flash-dt*5);e.spark-=dt;if(e.type==='node'){const boss=s.enemies.find(x=>x.id===e.parent&&!x.dead);if(!boss){e.dead=true;return}const a=e.slot+e.age*(boss.tier===2?1:-1)*.75,r=boss.radius+31;e.x=boss.x+Math.cos(a)*r;e.y=boss.y+Math.sin(a)*r;return}if(e.boss){this.updateBoss(e,dt);return}const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;let vx=0,vy=0;if(e.type==='seeker'||e.type==='splitter'||e.type==='mite'){vx=dx/d*e.speed;vy=dy/d*e.speed;if(e.type==='seeker'){const w=Math.sin(e.age*3+e.id)*16;vx+=-dy/d*w;vy+=dx/d*w}}else if(e.type==='gunner'){const q=d>190?1:d<135?-1:0;vx=dx/d*e.speed*q-dy/d*12;vy=dy/d*e.speed*q+dx/d*12;e.shoot-=dt;if(e.shoot<=0){this.aimed(e,s.wave>5?3:1,.16,122+s.wave*2);e.shoot=Math.max(1.3,2.25-s.wave*.06)}}else if(e.type==='charger'){if(e.mode==='idle'){e.ai-=dt;vx=dx/d*e.speed*.55;vy=dy/d*e.speed*.55;if(e.ai<=0&&d<280){e.mode='warn';e.ai=.72;e.charge=Math.atan2(dy,dx)}}else if(e.mode==='warn'){e.ai-=dt;if(e.ai<=0){e.mode='charge';e.ai=.5}}else{e.ai-=dt;vx=Math.cos(e.charge)*245;vy=Math.sin(e.charge)*245;if(e.ai<=0){e.mode='idle';e.ai=1.4+this.random.next()}}}e.x+=vx*dt;e.y+=vy*dt;const b=this.bounds();e.x=clamp(e.x,b.left-10,b.right+10);e.y=clamp(e.y,b.top-10,b.bottom+10);if(distance(e,p)<e.radius+p.radius)this.hurt(e.mode==='charge'?2:1,e)}
 updateBoss(e,dt){const s=this.state,p=s.player,ratio=e.hp/e.maxHp;e.phase=ratio>.66?1:ratio>.33?2:3;e.age+=0;const targetX=p.x+Math.cos(e.age*.37)*145,targetY=clamp(p.y-205+Math.sin(e.age*.51)*75,this.bounds().top+55,this.bounds().bottom-95),d=Math.hypot(targetX-e.x,targetY-e.y)||1;e.x+=(targetX-e.x)/d*e.speed*dt;e.y+=(targetY-e.y)/d*e.speed*dt;e.shoot-=dt;if(e.shoot<=0){if(e.tier===1){this.radial(e,8+e.phase*2,105+e.phase*9,e.rot);this.aimed(e,2+e.phase,.15,140);e.shoot=1.9-e.phase*.13}else{this.radial(e,12+e.phase*3,112+e.phase*10,e.rot);this.aimed(e,3+e.phase,.11,150);e.shoot=1.5-e.phase*.1}}e.summon-=dt;if(e.summon<=0&&s.enemies.length<13){for(let i=0;i<(e.tier===2?3:2);i++)this.spawn(this.random.pick(['seeker','gunner']));e.summon=4.7-e.phase*.25}if(e.tier===2&&ratio<.5&&!e.secondNodes){e.secondNodes=true;this.spawnNodes(e,2);this.cb.toast('SHIELD REFORMED')}if(distance(e,p)<e.radius+p.radius)this.hurt(1,e)}
 updateBullets(dt){const s=this.state,p=s.player,b=this.bounds();for(const x of s.bullets){x.age+=dt;x.life-=dt;x.x+=x.vx*dt;x.y+=x.vy*dt;if(x.x<b.left-80||x.x>b.right+80||x.y<b.top-80||x.y>b.bottom+80)x.dead=true;else if(!x.dead&&distance(x,p)<x.radius+p.radius){x.dead=true;this.hurt(1,x)}}}
 damage(e,amount,source){if(e.dead)return;e.hp-=amount;e.flash=1;if(e.hp<=0)this.kill(e,source)}
 kill(e,source){if(e.dead)return;const s=this.state;e.dead=true;if(e.type==='node'){const boss=s.enemies.find(x=>x.id===e.parent&&!x.dead);if(boss){boss.nodes=Math.max(0,boss.nodes-1);if(!boss.nodes){this.cb.toast('CORE EXPOSED');s.rings.push({x:boss.x,y:boss.y,r:5,max:95,life:.7,color:'#ffe288'})}}}s.kills++;s.combo=s.comboTime>0?s.combo+1:1;s.comboTime=2.15*(1+(s.levels.surge||0)*.5);s.maxCombo=Math.max(s.maxCombo,s.combo);const points=Math.floor(e.score*(1+Math.min(5,s.combo*.17)));s.score+=points;s.energy=Math.min(s.maxEnergy,s.energy+(e.boss?45:7));this.floater(e.x,e.y,`+${points}`,source==='burst'?'#ffe28a':e.color);this.particles(e.x,e.y,e.color,e.boss?34:12,e.boss?210:115);this.sound?.event('kill',e.boss?1:.6);if(e.type==='splitter'&&!e.child)for(let i=0;i<2;i++)this.spawn('mite',{x:e.x+(i?10:-10),y:e.y,child:true});if(s.levels.burst&&!e.boss)this.explode(e.x,e.y);if(s.levels.leech&&!e.boss){s.leech++;if(s.leech>=10&&s.hp<s.maxHp){s.leech-=10;s.hp++;this.floater(s.player.x,s.player.y-18,'+HULL','#74ffd0')}}if(e.boss){s.boss=null;this.flash=.45;this.shake=15}}
 explode(x,y){const s=this.state;s.rings.push({x,y,r:4,max:70,life:.4,color:'#ffe083'});for(const e of s.enemies)if(!e.dead&&!e.boss&&distance({x,y},e)<72+e.radius)this.damage(e,55,'burst');for(const b of s.bullets)if(distance({x,y},b)<72)b.dead=true}
 hurt(amount,source){const s=this.state;if(s.invuln>0||s.status!=='running')return;if(s.shield){s.shield=0;s.invuln=.8;s.rings.push({x:s.player.x,y:s.player.y,r:5,max:55,life:.4,color:'#78fff2'});this.floater(s.player.x,s.player.y-20,'SHIELD','#78fff2');return}s.hp=Math.max(0,s.hp-amount);s.invuln=1.1;this.shake=13;this.flash=.42;this.particles(s.player.x,s.player.y,'#ff557d',18,150);this.sound?.event('hurt');if(source){const a=Math.atan2(s.player.y-source.y,s.player.x-source.x);s.player.vx+=Math.cos(a)*90;s.player.vy+=Math.sin(a)*90}if(!s.hp)this.finish(false)}
 particles(x,y,color,count,speed=90){const s=this.state;if(!s)return;const limit=this.quality===2?170:this.quality===1?100:55;for(let i=0;i<Math.min(count,Math.max(0,limit-s.particles.length));i++){const a=this.random.next()*TAU,v=speed*(.25+this.random.next()*.75),life=.25+this.random.next()*.45;s.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life,max:life,color,size:.8+this.random.next()*2.2})}}
 floater(x,y,text,color){const s=this.state;s.floaters.push({x,y,text,color,life:.8,max:.8});if(s.floaters.length>18)s.floaters.shift()}
 waveClear(){const s=this.state;s.waveStarted=false;if(s.wave>=8){this.finish(true);return}s.status='upgrading';s.energy=Math.min(s.maxEnergy,s.energy+30);if(s.wave===4)s.hp=Math.min(s.maxHp,s.hp+1);s.pending=upgradeChoices(this.random,s.levels,3);if(!s.pending.length){s.wave++;s.status='running';this.beginWave();return}this.sound?.event('wave');this.cb.status('upgrading');this.cb.upgrade(s.pending,s.levels)}
 finish(victory){const s=this.state;if(!s||s.status==='result')return;this.pointer=null;this.anchor=null;s.status='result';s.victory=victory;this.sound?.stop();this.sound?.event(victory?'victory':'defeat');this.cb.status('result');this.cb.result({victory,score:Math.floor(s.score),wave:s.wave,maxCombo:s.maxCombo,time:s.clock,kills:s.kills,cuts:s.cuts,metrics:{...s.metrics},seed:s.seed})}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();this.w=Math.max(1,Math.round(r.width));this.h=Math.max(1,Math.round(r.height));const cap=this.quality===2?2:this.quality===1?1.5:1;let d=Math.min(devicePixelRatio||1,cap);if(this.w*this.h*d*d>2e6)d=Math.sqrt(2e6/(this.w*this.h));this.dpr=Math.max(1,d);this.canvas.width=Math.round(this.w*this.dpr);this.canvas.height=Math.round(this.h*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);if(this.state){const b=this.bounds(),p=this.state.player;p.x=clamp(p.x,b.left,b.right);p.y=clamp(p.y,b.top,b.bottom);if(this.w>this.h&&this.h<520)this.pause('orientation')}}
 loop(t){const dt=clamp((t-this.last)/1000,0,.05);this.last=t;if(this.state?.status==='running'){this.acc+=dt;let n=0;while(this.acc>=STEP&&n<3){this.update(STEP);this.acc-=STEP;n++}if(n===3)this.acc=0}else this.acc=0;this.render(t/1000);this.samples.push(dt*1000);if(this.samples.length>=240){const p=pct(this.samples,.95),avg=this.samples.reduce((a,b)=>a+b,0)/this.samples.length;this.samples=[];if(this.state&&this.quality>0&&(p>29||avg>23)){this.quality--;this.resize();this.cb.quality(this.quality,{p,avg})}}this.hudTimer+=dt;if(this.state&&this.hudTimer>.08){this.hudTimer=0;this.cb.hud(this.snapshotHud())}requestAnimationFrame(this.loop)}
 snapshotHud(){const s=this.state,b=s?.enemies.find(x=>x.boss&&!x.dead);return{status:s?.status||'idle',wave:s?.wave||1,score:formatNumber(s?.score||0),hp:s?.hp||0,maxHp:s?.maxHp||3,energy:s?s.energy/s.maxEnergy:1,combo:s?.combo||0,shield:s?.shield||0,boss:b?{name:b.name,hp:Math.max(0,b.hp/b.maxHp),shield:b.nodes>0}:null}}
 render(time){const c=this.ctx;c.save();c.setTransform(this.dpr,0,0,this.dpr,0,0);this.background(c,time);if(!this.state){c.restore();return}const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches||document.documentElement.classList.contains('reduce-motion'),sx=!reduce&&this.shake?Math.sin(time*89)*this.shake:0,sy=!reduce&&this.shake?Math.cos(time*73)*this.shake:0;c.translate(sx,sy);this.drawTrail(c);this.drawRings(c);this.drawBullets(c);this.drawEnemies(c,time);this.drawTether(c,time);this.drawPlayer(c,time);this.drawParticles(c);this.drawFloaters(c);c.translate(-sx,-sy);this.vignette(c);c.restore()}
 background(c,time){const g=c.createRadialGradient(this.w*.5,this.h*.45,20,this.w*.5,this.h*.45,Math.max(this.w,this.h)*.72);g.addColorStop(0,'#111d40');g.addColorStop(.55,'#070b1e');g.addColorStop(1,'#02030a');c.fillStyle=g;c.fillRect(0,0,this.w,this.h);c.save();c.globalAlpha=.13;c.strokeStyle='#5974b5';c.lineWidth=.5;for(let x=-40;x<this.w+40;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x+this.h*.05,this.h);c.stroke()}for(let y=-40+(time*4)%40;y<this.h+40;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(this.w,y);c.stroke()}c.restore();if(this.state)for(const s of this.state.stars){c.globalAlpha=s.a*(.65+Math.sin(time*1.5+s.p)*.35);c.fillStyle='#c6ddff';c.fillRect(s.x,(s.y+time*s.s*1.5)%this.h,s.s,s.s)}c.globalAlpha=1}
 drawTrail(c){const t=this.state.trail;if(t.length<2)return;c.save();c.lineCap='round';for(let i=t.length-1;i>0;i--){c.globalAlpha=(1-i/t.length)*.22;c.strokeStyle='#72fff1';c.lineWidth=1.4;c.beginPath();c.moveTo(t[i].x,t[i].y);c.lineTo(t[i-1].x,t[i-1].y);c.stroke()}c.restore()}
 drawTether(c,time){if(!this.anchor)return;const p=this.state.player,a=this.anchor,g=c.createLinearGradient(p.x,p.y,a.x,a.y);g.addColorStop(0,'#75fff1');g.addColorStop(.52,'#fff');g.addColorStop(1,'#aa7cff');c.save();c.strokeStyle=g;c.lineCap='round';c.shadowColor='#68fff1';c.shadowBlur=this.quality===2?16:6;c.globalAlpha=.32;c.lineWidth=14+(this.state.levels.width||0)*2;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(a.x,a.y);c.stroke();c.globalAlpha=.96;c.lineWidth=2.4+(this.state.levels.width||0)*.8;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(a.x,a.y);c.stroke();c.translate(a.x,a.y);c.strokeStyle='#b789ff';c.lineWidth=1.5;c.setLineDash([5,6]);c.lineDashOffset=-time*18;c.beginPath();c.arc(0,0,16+Math.sin(time*6)*2,0,TAU);c.stroke();c.setLineDash([]);c.globalAlpha=.38;c.beginPath();c.arc(0,0,31+Math.sin(time*3)*4,0,TAU);c.stroke();c.restore()}
 drawBullets(c){for(const b of this.state.bullets){c.save();c.translate(b.x,b.y);c.rotate(b.age*3);c.fillStyle='#fff';c.strokeStyle=b.color;c.lineWidth=2;c.shadowColor=b.color;c.shadowBlur=this.quality===2?9:3;polygon(c,4,b.radius,Math.PI/4);c.fill();c.stroke();c.restore()}}
 drawEnemies(c,time){for(const e of this.state.enemies){c.save();c.translate(e.x,e.y);c.rotate(e.rot);c.strokeStyle=e.flash?'#fff':e.color;c.fillStyle=e.color+'20';c.lineWidth=e.boss?3:2;c.shadowColor=e.color;c.shadowBlur=this.quality===2?(e.boss?18:9):3;if(e.boss){polygon(c,e.tier===1?8:10,e.radius,0);c.fill();c.stroke();c.rotate(-e.rot*2);polygon(c,e.tier===1?4:6,e.radius*.56,Math.PI/4);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(0,0,4+e.phase,0,TAU);c.fill()}else if(e.type==='seeker'){polygon(c,3,e.radius,-Math.PI/2);c.fill();c.stroke()}else if(e.type==='gunner'){polygon(c,4,e.radius,Math.PI/4);c.fill();c.stroke()}else if(e.type==='charger'){polygon(c,4,e.radius*1.1,0);c.fill();c.stroke()}else if(e.type==='splitter'){polygon(c,6,e.radius,0);c.fill();c.stroke()}else if(e.type==='node'){c.beginPath();c.arc(0,0,e.radius,0,TAU);c.stroke();c.beginPath();c.arc(0,0,e.radius*.35,0,TAU);c.fill()}else{polygon(c,5,e.radius,-Math.PI/2);c.fill();c.stroke()}c.restore();if(e.type==='charger'&&e.mode==='warn'){c.save();c.globalAlpha=.5+Math.sin(time*20)*.2;c.strokeStyle='#ffd36f';c.setLineDash([7,7]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x+Math.cos(e.charge)*320,e.y+Math.sin(e.charge)*320);c.stroke();c.restore()}if(!e.boss&&e.hp<e.maxHp){c.fillStyle='rgba(2,3,10,.75)';c.fillRect(e.x-e.radius,e.y-e.radius-8,e.radius*2,2);c.fillStyle=e.color;c.fillRect(e.x-e.radius,e.y-e.radius-8,e.radius*2*clamp(e.hp/e.maxHp,0,1),2)}}}
 drawPlayer(c,time){const s=this.state,p=s.player,blink=s.invuln>0&&Math.floor(time*13)%2===0;c.save();c.translate(p.x,p.y);c.rotate(Math.atan2(p.vy,p.vx));c.globalAlpha=blink?.3:1;c.fillStyle='#fff';c.strokeStyle='#73fff1';c.lineWidth=2;c.shadowColor='#5effee';c.shadowBlur=this.quality===2?18:7;c.beginPath();c.moveTo(12,0);c.lineTo(-9,-7);c.lineTo(-5,0);c.lineTo(-9,7);c.closePath();c.fill();c.stroke();if(s.shield){c.strokeStyle='#82fff3';c.setLineDash([4,5]);c.beginPath();c.arc(0,0,19+Math.sin(time*4)*2,0,TAU);c.stroke()}c.restore()}
 drawRings(c){for(const r of this.state.rings){c.save();c.globalAlpha=clamp(r.life*2.2,0,1);c.strokeStyle=r.color;c.lineWidth=2+r.life*3;c.shadowColor=r.color;c.shadowBlur=this.quality===2?14:4;c.beginPath();c.arc(r.x,r.y,r.r,0,TAU);c.stroke();c.restore()}}
 drawParticles(c){for(const p of this.state.particles){c.globalAlpha=clamp(p.life/p.max,0,1);c.fillStyle=p.color;c.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size)}c.globalAlpha=1}
 drawFloaters(c){c.textAlign='center';c.font='800 9px ui-sans-serif,system-ui';for(const f of this.state.floaters){c.globalAlpha=clamp(f.life/f.max,0,1);c.fillStyle=f.color;c.fillText(f.text,f.x,f.y)}c.globalAlpha=1}
 vignette(c){const g=c.createRadialGradient(this.w/2,this.h/2,Math.min(this.w,this.h)*.25,this.w/2,this.h/2,Math.max(this.w,this.h)*.72);g.addColorStop(.55,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,8,.73)');c.fillStyle=g;c.fillRect(0,0,this.w,this.h);if(this.flash){c.fillStyle=`rgba(160,230,255,${Math.min(.27,this.flash)})`;c.fillRect(0,0,this.w,this.h)}}
 testSnapshot(){const s=this.state;return s?{status:s.status,wave:s.wave,score:Math.floor(s.score),hp:s.hp,energy:+s.energy.toFixed(2),enemies:s.enemies.length,bullets:s.bullets.length,seed:s.seed,metrics:{...s.metrics}}:null}
 testWave(wave){if(!this.state)return;this.state.wave=clamp(Math.floor(wave),1,8);this.state.status='running';this.state.enemies.length=0;this.state.bullets.length=0;this.beginWave()}
 testClearWave(){if(this.state?.status!=='running')return;this.state.spawnLeft=0;this.state.enemies.length=0;this.state.bullets.length=0;this.state.waveStarted=true;this.state.waveIntro=0;this.state.clearTime=.76;this.update(STEP)}
 destroy(){this.stop();this.ro.disconnect()}
}
