import './style.css';
import { Game, PLACES, heightAt, distance, clamp, angleDelta } from './core.js';
import { SceneView } from './scene.js';
import { Soundscape } from './audio.js';
import { WEAPONS, SENA, EAST_CAMP, crossingText } from './content.js';
import { FrameMetrics } from './performance.js';
const frameMetrics=new FrameMetrics();

const $=id=>document.getElementById(id), SAVE_KEY='q-ash-pilgrim-v1', SETTINGS_KEY='q-ash-settings-v1';
let stored=null,settings={quality:'medium',volume:.45,assist:false,sensitivity:1,music:true};
try{stored=JSON.parse(localStorage.getItem(SAVE_KEY));const s=JSON.parse(localStorage.getItem(SETTINGS_KEY));if(s&&typeof s==='object')settings={...settings,...s};}catch{}
if(!['low','medium','high'].includes(settings.quality))settings.quality='medium';settings.volume=clamp(Number(settings.volume)||0,0,1);settings.sensitivity=clamp(Number(settings.sensitivity)||1,.5,2);
let game=new Game(stored),view,playing=false,paused=false,panelType='',lastFrame=0,accumulator=0,saveTimer=0,hudTimer=0,toastTimer=0,locationTimer=0,warningTimer=0,walkTimer=0;
game.assist=!!settings.assist;const audio=new Soundscape();audio.volume=settings.volume;audio.music=settings.music;
const input={x:0,z:0,sprint:false},keys=new Set(),stick={x:0,y:0},camera={id:null,x:0,y:0};let stickId=null,attackHeld=false,lastPad=[];const buttonPointers=new Map();
const svgPaths={attack:'M5 19 19 5M14 4l6 0v6M4 15l5 5M7 17l-4 4',dodge:'M4 13a8 8 0 1 1 8 7M4 13V7m0 6h6M12 8l3 4-3 4',skill:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',parry:'m12 3 8 4v6c0 4-8 8-8 8s-8-4-8-8V7Z',jump:'m6 11 6-7 6 7M12 4v15M6 21h12',heal:'M9 3h6M10 3v5L6 16q-2 5 6 5t6-5l-4-8V3M8 14h8',lock:'M3 8V3h5m8 0h5v5m0 8v5h-5m-8 0H3v-5M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8'};
for(const [key,path]of Object.entries(svgPaths)){const b=$(`${key}-button`);if(b)b.querySelector('b').innerHTML=`<svg viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;}
function notify(text){$('toast').textContent=text;$('toast').style.opacity='1';toastTimer=3.8;}
function save(){if(!playing)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(game.serialize()));}catch{notify('このブラウザーでは保存できません。旅の記録からセーブを書き出せます。');}}
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}}
function clearInput(){game.clearActionBuffer();buttonPointers.clear();for(const b of document.querySelectorAll('.pressed'))b.classList.remove('pressed');const pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected&&p.mapping==='standard');lastPad=pad?pad.buttons.map(b=>b.pressed):[];keys.clear();stick.x=stick.y=0;stickId=null;input.x=input.z=0;input.sprint=false;attackHeld=false;camera.id=null;$('stick').style.transform='';}
function closePanel(){paused=false;panelType='';$('panel-backdrop').classList.add('hidden');clearInput();if(playing){$('world').focus({preventScroll:true});audio.start();}}
function panel(kind,kicker,title,html){clearInput();paused=true;panelType=kind;$('panel-kicker').textContent=kicker;$('panel-title').textContent=title;$('panel-body').innerHTML=html;$('panel-backdrop').classList.remove('hidden');$('close-panel').focus({preventScroll:true});}
function activate(name,fn){$(name).addEventListener('click',fn);}
function startGame(fresh){if(fresh){game=new Game();game.assist=!!settings.assist;view.game=game;}playing=true;paused=false;$('title-screen').classList.add('hidden');$('hud').classList.remove('hidden');clearInput();audio.start();view.camera.position.set(game.player.x,game.player.y+5,game.player.z+10);view.yaw=.05;showLocation(PLACES[0]);if(!game.talked)notify('左で移動、右をドラッグで視点。灯守ミラを探そう。');save();$('world').focus();}
function showLocation(p){$('location').querySelector('small').textContent=p.en;$('location').querySelector('h2').textContent=p.name;$('location').style.opacity='1';locationTimer=4.5;}
activate('start',()=>{if(stored&&stored.version===1){panel('new','A NEW JOURNEY','新しい旅を始める',`<p>現在の旅のセーブを、新しい旅に置き換えます。</p><div class="panel-actions"><button id="confirm-new" class="primary">新しい旅を始める</button><button id="cancel-new">戻る</button></div>`);activate('confirm-new',()=>{closePanel();startGame(true);});activate('cancel-new',closePanel);}else startGame(true);});
activate('continue',()=>startGame(false));activate('close-panel',closePanel);
activate('respawn',()=>{game.respawn();view.snapCamera();$('death-screen').classList.add('hidden');clearInput();save();});
function dialogue(npc='keeper'){if(npc==='ferryman'){senaDialogue();return;}const delivered=game.relicDelivered;panel('dialogue','WINDFALL HAVEN','火を待つ人',`<div class="dialogue-speaker">灯守 ミラ</div><p class="dialogue-text">${game.ending?game.ending==='release'?'朝、窓を開けたら、灰が花みたいに舞っていた。火はもう、誰か一人のものじゃないんだね。':'門に、火が戻ったね。ありがとう。でも今度こそ、王冠が誰かを焼かないように見届けなくちゃ。':game.bossDefeated?'番人は、火を守りたかっただけなのかもしれない。最後に火をどうするかは、あなたが決めて。':delivered?'それは……父がつけていた巡礼の印。帰ってこなかった人にも、道の続きを歩いてくれる人がいたんだね。ありがとう。':'この谷の火は、北の王冠に吸い上げられたの。森、水殿、廃塔。三つの灯火をともせば、門は開く。<br><br>番人は、まだ王を待っている。あなたなら、その終わらない夜を止められるかもしれない。'}</p><div class="journal"><h3>灯守の願い</h3><p>${delivered?'巡礼の遺物を届けた。ミラは父の足跡を知った。':game.relic?'鞄の中に、ミラが探していた巡礼の印がある。':'東の草原に、父の巡礼の印が落ちているはず。見つけたら、どうか持ち帰って。'}</p>${game.crossingChoice==='haven'?'<p>セナから薬草が届いたよ。村の薬師が霊薬に加えてくれた。傷の治りがよくなったでしょう？</p>':''}</div><div class="panel-actions">${game.relic&&!delivered?'<button id="deliver-relic" class="primary">父の巡礼の印を渡す</button>':''}<button id="dialogue-leave" class="primary">${game.ending?'また風を追ってくる':'火を探しに行く'}</button><button id="dialogue-tips">戦い方を聞く</button></div>`);if(game.relic&&!delivered)activate('deliver-relic',()=>{if(game.deliverRelic()){save();dialogue();}});activate('dialogue-leave',()=>{closePanel();save();});activate('dialogue-tips',()=>{panel('tips','MIRA’S ADVICE','刃より先に、敵を見る',`<p>敵の足元が橙色に光ったら攻撃の予兆。距離を取るか、回避しよう。受け流しは敵の方を向き、攻撃が届く直前に使う。</p><p>回避にも斬撃にもスタミナを使う。使い切る前に少し離れれば、すぐに戻る。残火の力は周りの敵をひるませる。</p><p>番人の広い衝撃波は、跳躍でも越えられる。灯火で休むと生命力と霊薬が回復する。</p><div class="panel-actions"><button id="tips-close" class="primary">覚えておく</button></div>`);activate('tips-close',closePanel);});}
function senaDialogue(){
  const done=game.crossingChoice;
  const speech=done==='haven'?'ミラが荷を受け取ってくれた。寝込んでいた人たちも、今夜は眠れるだろう。旅人には、俺の手持ちを少しずつ分けるよ。':done==='road'?'道に、また野営の灯りがともった。誰でも薬を取っていける。集落の人には、次の荷を俺が必ず届ける。':game.supplies?'戻ってきたんだな。その荷には薬草が入っている。村の病人に届けるか、道を歩く人たちに分けるか……今ある分では、どちらも十分には足りない。':game.crossingStarted?'橋はまだ渡れる。東岸の荷車には、弓を構えた兵がいる。弦を引いたら横へ動くんだ。真っ直ぐ逃げるより、矢を外しやすい。':'水が増えてから、荷車が戻らない。あの薬草を待っている人がいるんだ。東の岸まで見に行ってくれないか。この槍なら、少し離れて戦える。';
  panel('sena','THE RIVER KEEPS ITS PROMISE','川の向こうの約束',`<div class="dialogue-speaker">渡し守 セナ</div><p class="dialogue-text">${speech}</p><div class="journal"><p>${crossingText(game)}</p></div>${game.supplies&&!done?'<button class="choice" id="supplies-haven">集落の病人に届ける<span>霊薬の回復量が15増える。薬草は風待ちの集落へ。</span></button><button class="choice" id="supplies-road">道を歩く旅人に分ける<span>灯火で霊薬を4本まで補充。橋の近くに野営地が戻る。</span></button>':''}<div class="panel-actions">${!done&&!game.supplies?`<button class="primary" id="sena-accept">${game.crossingStarted?'荷車への道を確かめる':'槍を受け取り、引き受ける'}</button>`:''}<button id="sena-leave">また会おう</button></div>`);
  if(!done&&!game.supplies)activate('sena-accept',()=>{if(game.startCrossingQuest()){save();closePanel();notify('川の向こうの約束 — 東岸の荷車へ');}});
  if(game.supplies&&!done)for(const choice of ['haven','road'])activate(`supplies-${choice}`,()=>{if(game.resolveCrossing(choice)){save();senaDialogue();}});
  activate('sena-leave',closePanel);
}
function pack(){const p=game.player;panel('pack','THE PILGRIM’S JOURNAL','旅の記録',`<div class="stats-grid"><div class="stat"><small>巡礼者</small><strong>Lv.${p.level}</strong></div><div class="stat"><small>灰の欠片</small><strong>${p.ash}</strong></div><div class="stat"><small>生命力</small><strong>${Math.ceil(p.hp)} / ${p.maxHp}</strong></div><div class="stat"><small>経験</small><strong>${p.xp} / ${game.xpNeeded()}</strong></div></div><div class="weapon-list">${Object.entries(WEAPONS).map(([id,w])=>`<div class="weapon-card ${p.weaponType===id?'equipped':''}"><h3>${w.name}</h3><p>${w.description}</p><small>間合い ${w.reach} m · スタミナ ${w.cost}</small><button id="equip-${id}" ${!game.weapons.includes(id)||p.weaponType===id?'disabled':''}>${p.weaponType===id?'装備中':game.weapons.includes(id)?'装備する':id==='spear'?'森の灯火か渡し守から入手':'廃塔の灯火で入手'}</button></div>`).join('')}</div><div class="upgrade-list">${[['weapon','武器の鍛錬','すべての近接武器の威力を高める'],['vigor','生命の器','生命力の上限と霊薬の効果を高める'],['agility','風の足取り','移動とスタミナ回復を速める']].map(([id,name,desc])=>`<div class="upgrade-card"><h3>${name} +${p[id]}</h3><p>${desc}</p><button id="upgrade-${id}" ${p[id]>=5||p.ash<60+p[id]*45?'disabled':''}>${p[id]>=5?'最大まで強化済み':`強化する · ✧ ${60+p[id]*45}`}</button></div>`).join('')}</div><div class="journal"><h3>${game.quest().title}</h3><p>${game.quest().text}</p><p>灯火 ${game.lit.length-1}/3 · 発見した場所 ${game.discovered.length}/5 · 宝箱 ${game.pickups.filter(l=>l.type==='chest'&&l.taken).length}/${game.pickups.filter(l=>l.type==='chest').length} · 巡礼の遺物 ${game.relicDelivered?'ミラへ届けた':game.relic?'ミラへ届けよう':'未発見'}</p></div><div class="journal"><h3>川の向こうの約束</h3><p>${crossingText(game)}</p><div class="panel-actions"><button id="track-main" ${game.trackedQuest==='main'?'disabled':''}>王冠への旅を追う</button>${(game.crossingStarted||game.supplies)&&!game.crossingChoice?`<button id="track-crossing" ${game.trackedQuest==='crossing'?'disabled':''}>薬草の荷を追う</button>`:''}</div></div><p>露草 ${p.herbs}個 / 露の霊薬 ${p.potions}本${game.crossingChoice==='haven'?' · 集落の薬師：回復量 +15':game.crossingChoice==='road'?' · 旅人の薬箱：休息で4本補充':''}</p><div class="panel-actions"><button id="craft" ${p.herbs<2||p.potions>=6?'disabled':''}>露草2個で霊薬を調合</button><button id="export-save">セーブを書き出す</button><button id="import-save">セーブを読み込む</button><input type="file" id="save-file" accept="application/json,.json" hidden></div><p class="subtle">旅の進行はこの端末のブラウザーに自動保存されます。別の端末へ移すときはセーブを書き出してください。</p>`);
    for(const id of Object.keys(WEAPONS))activate(`equip-${id}`,()=>{if(game.equipWeapon(id)){save();pack();}else notify('動作が終わってから装備を替えよう');});
    activate('track-main',()=>{game.trackQuest('main');pack();});if($('track-crossing'))activate('track-crossing',()=>{game.trackQuest('crossing');pack();});
    for(const id of ['weapon','vigor','agility'])activate(`upgrade-${id}`,()=>{if(game.upgrade(id)){audio.play('level');save();pack();}});
    activate('craft',()=>{game.craft();save();pack();});activate('export-save',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(game.serialize(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Q-ash-pilgrim-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});activate('import-save',()=>$('save-file').click());$('save-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>100000){notify('セーブファイルが大きすぎます');return;}try{const s=JSON.parse(await f.text());if(s.version!==1||!s.player)throw Error();game=new Game(s);game.assist=!!settings.assist;view.game=game;view.snapCamera();save();closePanel();notify('旅の記録を読み込んだ');}catch{notify('灰の巡礼のセーブファイルを選んでください');}};
}
function drawMap(){const c=$('map-canvas'),ctx=c.getContext('2d'),W=600,H=650;c.width=W;c.height=H;const toX=x=>W/2+x*.91,toY=z=>(z+295)*1.24;ctx.fillStyle='#b9b59a';ctx.fillRect(0,0,W,H);for(let x=0;x<W;x+=5)for(let y=0;y<H;y+=5){const wx=(x-W/2)/.91,wz=y/1.24-295,h=heightAt(wx,wz);ctx.fillStyle=`rgba(43,65,58,${clamp(h*.009+.07,0,.46)})`;ctx.fillRect(x,y,5,5);}ctx.beginPath();for(let z=-260;z<=225;z+=4){const x=166+Math.sin(z*.017)*23;ctx.lineTo(toX(x),toY(z));}ctx.strokeStyle='#557e7b';ctx.lineWidth=11;ctx.stroke();ctx.beginPath();for(let z=-250;z<115;z+=5)ctx.lineTo(toX(Math.sin(z*.035)*7),toY(z));ctx.strokeStyle='#eee0ba';ctx.lineWidth=3;ctx.setLineDash([4,4]);ctx.stroke();ctx.setLineDash([]);ctx.font='12px serif';ctx.textAlign='center';for(const p of PLACES){const x=toX(p.x),y=toY(p.z),lit=game.lit.includes(p.id);ctx.fillStyle=lit?'#eddb9e':'#394f4d';ctx.beginPath();ctx.arc(x,y,lit?7:5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#39483f';ctx.stroke();ctx.fillStyle='#2b3b36';ctx.fillText(p.name,x,y-15);}if(game.metSena){ctx.fillStyle='#526558';ctx.beginPath();ctx.arc(toX(SENA.x),toY(SENA.z),5,0,Math.PI*2);ctx.fill();ctx.fillText('渡し守セナ',toX(SENA.x),toY(SENA.z)-12);}if(game.crossingStarted||game.supplies){ctx.strokeStyle='#8b523b';ctx.strokeRect(toX(EAST_CAMP.x)-5,toY(EAST_CAMP.z)-5,10,10);ctx.fillText('東岸の荷車',toX(EAST_CAMP.x),toY(EAST_CAMP.z)-13);}const p=game.player;ctx.save();ctx.translate(toX(p.x),toY(p.z));ctx.rotate(-p.angle);ctx.fillStyle='#ab4f34';ctx.beginPath();ctx.moveTo(0,10);ctx.lineTo(-6,-7);ctx.lineTo(6,-7);ctx.closePath();ctx.fill();ctx.restore();ctx.font='20px Georgia';ctx.fillStyle='#374d45';ctx.fillText('N',W-35,40);ctx.beginPath();ctx.moveTo(W-35,48);ctx.lineTo(W-35,81);ctx.stroke();ctx.font='10px sans-serif';ctx.fillText('灰冠の地',60,30);ctx.fillText('約100 m',70,H-20);ctx.fillRect(24,H-38,91,1);}
function mapPanel(){panel('map','A LAND WITHOUT A KING','灰冠の地',`<div class="map-layout"><canvas id="map-canvas" class="world-map" aria-label="谷の地図。北に灰冠の門、西に琥珀の森、東に水殿、中央北に廃塔。"></canvas><div class="map-places">${PLACES.map(p=>`<button class="map-place ${game.lit.includes(p.id)?'active':''}" id="place-${p.id}">${p.name}<small>${game.lit.includes(p.id)?'灯火へ移動':game.discovered.includes(p.id)?'発見済み · 火は消えている':'未踏の地'}</small></button>`).join('')}<p class="subtle">赤い矢印は現在地。ともした灯火には、敵が近くにいなければ移動できます。</p></div></div>`);drawMap();for(const p of PLACES)activate(`place-${p.id}`,()=>{if(game.lit.includes(p.id)){if(game.fastTravel(p.id)){closePanel();save();showLocation(p);}}else notify(`${p.name}までは約 ${Math.round(distance(game.player,p))} m`);});}
function settingsPanel(){const measured=frameMetrics.snapshot();panel('settings','REST A MOMENT','操作と設定',`<div class="setting-row"><span>描画品質<small>動きが重いときは「軽量」に</small></span><select id="quality"><option value="low">軽量</option><option value="medium">標準</option><option value="high">高品質</option></select></div><div class="setting-row"><span>音量</span><select id="volume"><option value="0">消音</option><option value="0.25">小</option><option value="0.45">標準</option><option value="0.8">大</option></select></div><div class="setting-row"><span>音楽</span><select id="music"><option value="true">あり</option><option value="false">環境音のみ</option></select></div><div class="setting-row"><span>カメラ感度</span><select id="sensitivity"><option value="0.6">低め</option><option value="1">標準</option><option value="1.6">高め</option></select></div><div class="setting-row"><span>旅人の加護<small>受けるダメージを軽減する</small></span><select id="assist"><option value="false">なし</option><option value="true">あり</option></select></div><div class="journal"><h3>この端末での動作</h3><p>${measured?`直近 ${measured.windowSeconds.toFixed(1)} 秒：平均 ${measured.averageFps.toFixed(1)} fps · 遅いフレーム ${measured.p95FrameMs.toFixed(1)} ms（95%点）`:'旅を始めると、実際に表示されたフレームの間隔を記録します。'}</p><p class="subtle">動きが重いときは描画品質を下げて確認できます。休止中の時間は含めません。</p><button id="export-performance" ${measured?'':'disabled'}>動作の記録を書き出す</button></div><div class="control-grid"><span>スマホ：左スティックで移動<br>右の空いている場所をドラッグで視点<br>各アクションボタンをタップ<br>スティックを大きく倒すと走る</span><span>PC：WASD 移動 / Shift 走る<br>J 斬撃 / Space 回避 / K 受け流し<br>L 残火 / R 回復 / Q 跳躍 / F 注視<br>E 調べる / M 地図 / I 記録 / Esc 休止</span></div><p class="subtle">ゲームパッドにも対応。左スティックで移動、右で視点。A 回避 / X 斬撃 / Y 残火 / B 調べる。<br>横向きで広く見渡せます。縦向きでも遊べます。</p><div class="panel-actions"><button id="settings-close" class="primary">${playing?'旅に戻る':'戻る'}</button><button id="fullscreen">全画面にする</button>${playing?'<button id="to-title">保存してタイトルへ</button>':''}</div>`);
    for(const k of ['quality','volume','music','sensitivity','assist']){if($(k).querySelector(`option[value="${settings[k]}"]`))$(k).value=String(settings[k]);$(k).onchange=()=>{settings[k]=['volume','sensitivity'].includes(k)?Number($(k).value):['music','assist'].includes(k)?$(k).value==='true':$(k).value;game.assist=settings.assist;audio.setVolume(settings.volume);audio.music=settings.music;view?.setQuality(settings.quality);saveSettings();};}
    activate('export-performance',()=>{const report={game:'Q — 灰の巡礼',version:'0.3.0',recordedAt:new Date().toISOString(),browser:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight,devicePixelRatio},quality:settings.quality,frames:frameMetrics.snapshot(),progress:{region:$('region').textContent,level:game.player.level},note:'Browser frame intervals during active play; not a GPU timer. No account or save data included.'};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Q-device-performance.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
    activate('settings-close',closePanel);activate('fullscreen',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('この端末ではブラウザーの全画面操作を使ってください');}});if(playing)activate('to-title',()=>{save();stored=game.serialize();closePanel();playing=false;$('hud').classList.add('hidden');$('title-screen').classList.remove('hidden');$('continue').classList.remove('hidden');});}
function endingChoice(){panel('ending-choice','THE LAST EMBER','火を、誰のものにするか',`<p class="dialogue-text">王のいない王冠に、最後の火が残っている。谷を照らすことも、誰にも縛られない風に返すこともできる。</p><button class="choice" id="ending-restore">王冠に火を戻す<span>集落の夜を、確かな灯りで照らす。灯守たちが火を守り継ぐ。</span></button><button class="choice" id="ending-release">火を風に放つ<span>王冠の力を手放し、谷のすべての人に小さな火を分ける。</span></button>`);for(const k of ['restore','release'])activate(`ending-${k}`,()=>{game.chooseEnding(k);save();closePanel();});}
function ending(choice){panel('ending','CHAPTER I · COMPLETE',choice==='release'?'名もなき火の朝':'火を継ぐ人たち',`<p class="dialogue-text">${choice==='release'?'火は、無数の光になって谷を渡った。<br>誰のものでもない温もりが、一つずつ窓にともる。<br><br>王冠は空になった。<br>それでも、この朝を寒いと言う者はいなかった。':'王冠に戻った火は、かつてより小さかった。<br>ミラはそれを見て、初めて笑った。<br><br>「一人で守らなくても、いいんだね」<br>新しい灯守たちの夜が、静かに始まった。'}</p><p>第一章「残り火の谷」完了。谷の探索は引き続き楽しめます。</p><div class="panel-actions"><button id="ending-close" class="primary">風のつづきを歩く</button></div>`);activate('ending-close',closePanel);}
activate('map-button',mapPanel);activate('pack-button',pack);activate('pause-button',settingsPanel);activate('title-settings',settingsPanel);
function action(name){if(!playing||paused||game.player.dead)return;if(['attack','dodge','parry','jump'].includes(name))game.requestAction(name,input);if(name==='skill')game.skill();if(name==='heal')game.heal();if(name==='interact')game.interact();if(name==='lock'){const candidates=game.enemies.filter(e=>!e.dead&&!(e.type==='boss'&&game.lit.length<4)&&distance(game.player,e)<25&&game.canReach(game.player,e)).sort((a,b)=>distance(game.player,a)-distance(game.player,b));game.locked=game.locked?null:candidates[0]?.id||null;}}
for(const key of ['attack','dodge','parry','jump','skill','heal','lock']){
  const b=$(`${key}-button`);
  b.addEventListener('pointerdown',e=>{if(!playing||paused||game.player.dead||buttonPointers.has(key))return;e.preventDefault();buttonPointers.set(key,e.pointerId);b.setPointerCapture(e.pointerId);action(key);b.classList.add('pressed');if(key==='attack')attackHeld=true;});
  for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{if(buttonPointers.get(key)!==e.pointerId)return;buttonPointers.delete(key);b.classList.remove('pressed');if(key==='attack')attackHeld=false;});
}
activate('interact',()=>action('interact'));
const joystick=$('joystick');function moveStick(e){if(e.pointerId!==stickId)return;const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2;const max=r.width*.37,d=Math.hypot(dx,dy);stick.x=dx/Math.max(max,d);stick.y=dy/Math.max(max,d);$('stick').style.transform=`translate(${stick.x*max}px,${stick.y*max}px)`;}
joystick.addEventListener('pointerdown',e=>{if(!playing||paused||stickId!==null)return;e.preventDefault();stickId=e.pointerId;joystick.setPointerCapture(e.pointerId);moveStick(e);});joystick.addEventListener('pointermove',moveStick);for(const event of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(event,e=>{if(e.pointerId===stickId){stickId=null;stick.x=stick.y=0;$('stick').style.transform='';}});
for(const el of [$('world'),$('camera-zone')]){el.addEventListener('pointerdown',e=>{if(!playing||paused||camera.id!==null)return;if(e.button===2){action('parry');return;}camera.id=e.pointerId;camera.x=e.clientX;camera.y=e.clientY;el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',e=>{if(e.pointerId!==camera.id)return;view.yaw-=(e.clientX-camera.x)*.006*settings.sensitivity;view.pitch=clamp(view.pitch+(e.clientY-camera.y)*.004*settings.sensitivity,-.12,1.1);camera.x=e.clientX;camera.y=e.clientY;});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,e=>{if(e.pointerId===camera.id)camera.id=null;});}
document.addEventListener('contextmenu',e=>e.preventDefault());$('world').addEventListener('wheel',e=>{e.preventDefault();view.zoom=clamp(view.zoom+e.deltaY*.01,5,17);},{passive:false});
document.addEventListener('keydown',e=>{if(['Tab'].includes(e.code)&&paused){const focusable=$('panel').querySelectorAll('button:not([disabled]),select,input:not([hidden])');if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}if(e.code==='Escape'){e.preventDefault();if(paused)closePanel();else if(playing)settingsPanel();return;}if(!playing||paused)return;const binds={KeyJ:'attack',Space:'dodge',KeyK:'parry',KeyQ:'jump',KeyL:'skill',KeyR:'heal',KeyE:'interact',KeyF:'lock'};if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat&&!keys.has(e.code))return;keys.add(e.code);if(e.repeat)return;if(binds[e.code])action(binds[e.code]);if(e.code==='KeyM')mapPanel();if(e.code==='KeyI')pack();});
document.addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{clearInput();if(playing&&!game.player.dead&&!paused)settingsPanel();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){save();audio.suspend();if(playing&&!paused&&!game.player.dead)settingsPanel();}});addEventListener('pagehide',save);
function readInput(dt){
  let x=stick.x+(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z=stick.y+(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);
  let sprint=keys.has('ShiftLeft')||keys.has('ShiftRight')||Math.hypot(stick.x,stick.y)>.88;
  const actions=[],pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected&&p.mapping==='standard');
  if(pad){
    const axis=i=>Number.isFinite(pad.axes[i])?pad.axes[i]:0;
    if(Math.abs(axis(0))>.18)x+=axis(0);if(Math.abs(axis(1))>.18)z+=axis(1);
    if(Math.abs(axis(2))>.15)view.yaw-=axis(2)*dt*2;if(Math.abs(axis(3))>.15)view.pitch=clamp(view.pitch+axis(3)*dt*1.4,-.12,1.1);
    for(const [i,name]of [[0,'dodge'],[1,'interact'],[2,'attack'],[3,'skill'],[4,'parry'],[5,'lock'],[6,'heal'],[7,'jump']])if(pad.buttons[i]?.pressed&&!lastPad[i])actions.push(name);
    lastPad=pad.buttons.map(b=>b.pressed);sprint||=!!pad.buttons[10]?.pressed;
  }else lastPad=[];
  const a=view.yaw;input.x=x*Math.cos(a)+z*Math.sin(a);input.z=z*Math.cos(a)-x*Math.sin(a);input.sprint=sprint;
  for(const name of actions)action(name);
  if(attackHeld||keys.has('KeyJ'))game.requestAction('attack',input);
  if(keys.has('ArrowLeft'))view.yaw+=dt*1.5;if(keys.has('ArrowRight'))view.yaw-=dt*1.5;
}
function handleEvents(){for(const e of game.events.splice(0)){audio.play(e.type);if(e.type==='notice')notify(e.text);if(e.type==='discover')showLocation(e.place);if(e.type==='save')save();if(e.type==='dialogue'){dialogue(e.npc);save();}if(e.type==='rest')pack();if(e.type==='travel'){view.snapCamera();clearInput();}if(e.type==='endingChoice')endingChoice();if(e.type==='ending')ending(e.choice);if(e.type==='death'){$('death-screen').classList.remove('hidden');clearInput();save();}if(e.type==='warning'){$('combat-hint').textContent=e.text;warningTimer=1.8;}if(e.type==='hurt'){$('hurt').style.opacity='.8';setTimeout(()=>$('hurt').style.opacity='0',150);}
    if(['hit','kill','skill','heal','perfect','hurt','beacon'].includes(e.type)){view.effect(e.type,e.x??game.player.x,e.z??game.player.z);if(e.type==='hit'){const pos=view.project(e.x,heightAt(e.x,e.z)+2,e.z);if(pos.visible){const n=document.createElement('span');n.className='damage-float';n.textContent=e.amount;n.style.left=`${pos.x}px`;n.style.top=`${pos.y}px`;$('damage-numbers').append(n);setTimeout(()=>n.remove(),750);}}}}
}
function updateHud(){const p=game.player;$('hp').style.transform=`scaleX(${p.hp/p.maxHp})`;$('stamina').style.transform=`scaleX(${p.stamina/100})`;$('energy').style.transform=`scaleX(${p.energy/100})`;$('hp-text').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('rank').textContent=`巡礼者 · Lv.${p.level}`;$('weapon-label').textContent=game.weaponStats().name;$('attack-button').querySelector('small').textContent=p.weaponType==='spear'?'刺突':'斬撃';$('potions').textContent=p.potions;$('currency').textContent=`✧ ${p.ash}`;const q=game.quest();$('quest-category').textContent=game.trackedQuest==='crossing'?'SIDE JOURNEY':'MAIN JOURNEY';$('quest-title').textContent=q.title;$('quest-text').textContent=q.text;const s=game.nearestInteract();$('interact').classList.toggle('hidden',!s);if(s)$('interact').querySelector('span').textContent=s.name;
  const deg=((-view.yaw*180/Math.PI)%360+360)%360;const directions=['北','北東','東','南東','南','南西','西','北西'];$('heading').textContent=`·  ${directions[Math.round(deg/45)%8]}  ·`;if(q.target){const bearing=Math.atan2(p.x-q.target.x,p.z-q.target.z),delta=angleDelta(bearing,view.yaw);$('waypoint').style.left=`${50-clamp(delta,-1.5,1.5)*30}%`;$('waypoint').textContent=`◆ ${Math.round(distance(p,q.target))}m`;}else $('waypoint').textContent='';
  const nearest=PLACES.reduce((a,b)=>distance(p,a)<distance(p,b)?a:b);$('region').textContent=distance(p,nearest)<45?nearest.name:'残り火の谷';$('time').textContent=game.day<.25?'黎明':game.day<.52?'昼':game.day<.76?'夕暮れ':'夜';const boss=game.enemies.find(e=>e.type==='boss');$('boss').classList.toggle('hidden',boss.dead||distance(p,boss)>33||game.lit.length<4);$('boss-hp').style.transform=`scaleX(${boss.hp/boss.maxHp})`;const lock=game.enemies.find(e=>e.id===game.locked&&!e.dead);if(lock){const v=view.project(lock.x,lock.y+(lock.type==='boss'?4:1.5),lock.z);$('target-tag').style.display=v.visible?'block':'none';$('target-tag').style.left=`${v.x}px`;$('target-tag').style.top=`${v.y}px`;}else $('target-tag').style.display='none';$('skill-button').style.opacity=p.energy<40||p.skillCooldown>0?'.35':'1';$('heal-button').style.opacity=p.potions===0?'.35':'1';
  for(const npc of [{id:'keeper',x:7,z:80,name:'灯守 ミラ'},SENA]){let el=$(`npc-${npc.id}`);if(!el){el=document.createElement('div');el.id=`npc-${npc.id}`;el.className='npc-label';$('enemy-labels').append(el);}const point=view.project(npc.x,heightAt(npc.x,npc.z)+2.7,npc.z);el.style.display=point.visible&&distance(game.player,npc)<18?'block':'none';el.style.left=`${point.x}px`;el.style.top=`${point.y}px`;el.textContent=npc.id==='ferryman'?'渡し守 セナ':npc.name;}
  for(const e of game.enemies){let el=$(`health-${e.id}`);if(!el){el=document.createElement('div');el.id=`health-${e.id}`;el.className='enemy-health';el.innerHTML='<span></span><i><b></b></i>';$('enemy-labels').append(el);}const v=view.project(e.x,e.y+(e.type==='wolf'?1.8:2.55),e.z),visible=!e.dead&&e.type!=='boss'&&distance(p,e)<20&&v.visible;el.style.display=visible?'block':'none';if(visible){el.style.left=`${v.x}px`;el.style.top=`${v.y}px`;el.querySelector('span').textContent=e.type==='wolf'?'灰を喰う獣':e.type==='ranger'?'岸辺の弓兵':'火を失った兵';el.querySelector('b').style.transform=`scaleX(${e.hp/e.maxHp})`;}}
}
function frame(now){requestAnimationFrame(frame);const frameMs=now-(lastFrame||now),dt=Math.min(frameMs/1000,.05);lastFrame=now;if(!view||document.hidden)return;if(playing&&!paused&&!game.player.dead){frameMetrics.record(frameMs);readInput(dt);accumulator+=dt;while(accumulator>=1/60){game.tick(1/60,input);accumulator-=1/60;}saveTimer+=dt;if(saveTimer>15){save();saveTimer=0;}walkTimer-=dt;if(game.player.moving&&game.player.grounded&&walkTimer<=0){audio.noise(.05,.025,500);walkTimer=input.sprint?.24:.35;}}else accumulator=0;
  handleEvents();view.update(dt,playing);if(playing){hudTimer+=dt;if(hudTimer>.075){updateHud();hudTimer=0;}const combat=game.enemies.some(e=>!e.dead&&['chase','windup','strike'].includes(e.state)&&distance(e,game.player)<15);if(!paused)audio.tick(game.time,combat);}
  if(toastTimer>0&&(toastTimer-=dt)<=0)$('toast').style.opacity='0';if(locationTimer>0&&(locationTimer-=dt)<=0)$('location').style.opacity='0';if(warningTimer>0&&(warningTimer-=dt)<=0)$('combat-hint').textContent='';
}
try{view=new SceneView($('world'),game,settings);$('start').disabled=false;$('start').textContent='旅を始める';if(stored&&stored.version===1)$('continue').classList.remove('hidden');requestAnimationFrame(frame);}catch(e){console.error(e);$('fatal-message').textContent='WebGL 2に対応したブラウザーで開いてください。別のアプリを閉じて読み直すと改善することがあります。詳細: '+e.message;$('fatal').classList.remove('hidden');}

// Optional agent access to the same visible journal and crafting actions.
if(document.modelContext?.registerTool){
  const life=new AbortController();addEventListener('pagehide',()=>life.abort(),{once:true});
  const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  register({name:'read_pilgrim_journey',title:'旅の進行を読む',description:'Read this game’s current chapter objective, inventory and lit checkpoints. Does not change or start the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({playing,paused,level:game.player.level,objective:game.quest().text,lit:game.lit,ash:game.player.ash,herbs:game.player.herbs,potions:game.player.potions,ending:game.ending})});
  register({name:'open_pilgrim_journal',title:'旅の記録を開く',description:'Pause the active game and open its visible journal. Does not start a new game.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!playing||game.player.dead)throw Error('Start or resume a living character first.');pack();return{panel:'journal',paused:true};}});
  register({name:'craft_pilgrim_potion',title:'霊薬を調合する',description:'Spend exactly 2 herbs from the current inventory to craft one healing potion. Maximum 6 potions. This saves the changed inventory.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!playing||game.player.dead||game.player.herbs<2||game.player.potions>=6)throw Error('Cannot craft: active game, 2 herbs and a free potion slot are required.');game.craft();save();pack();return{herbs:game.player.herbs,potions:game.player.potions};}});
}
