import{formatNumber,formatTime,recordRun}from'./core.js';
import{Game}from'./game.js';
import{Sound}from'./audio.js';
import{load,reset,save as store}from'./storage.js';
const $=q=>document.querySelector(q),screens=[...document.querySelectorAll('.screen')],canvas=$('#canvas'),hud=$('#hud');
let data=load(),run={seed:1},toastTimer=0,resetTimer=0,tutorialStep=0;
const show=id=>{for(const s of screens)s.classList.toggle('active',s.id===id)};
const hudVisible=value=>{hud.classList.toggle('hidden',!value);hud.setAttribute('aria-hidden',String(!value))};
const persist=()=>{data=store(data);records()};
const vibrate=p=>{if(data.settings.vibration)try{navigator.vibrate?.(p)}catch{}};
function toast(text,time=1600){clearTimeout(toastTimer);const e=$('#toast');e.textContent=text;e.classList.add('show');toastTimer=setTimeout(()=>e.classList.remove('show'),time)}
const sound=new Sound(()=>data.settings);
const game=new Game(canvas,{sound,reduced:()=>data.settings.reduced,callbacks:{
 status(status,reason){if(status==='running'){show('');hudVisible(true)}else if(status==='paused'){const copy=reason==='orientation'?'縦向きに戻してから再開してください。':reason==='visibility'||reason==='pagehide'?'画面を離れたため、安全な位置で停止しました。':'光路を保持しています。準備ができたら再開してください。';$('#pause-copy').textContent=copy;show('paused');hudVisible(true)}else if(status==='upgrading'){show('upgrade');hudVisible(true);vibrate([18,30,18])}else if(status==='idle')hudVisible(false)},
 hud(s){const energy=Math.round(s.energy*100);$('#wave').textContent=`${String(s.wave).padStart(2,'0')} / 08`;$('#threat').textContent=s.threat;$('#score').textContent=s.score;$('#energy').style.transform=`scaleX(${s.energy})`;$('#tether-meter').setAttribute('aria-valuenow',String(energy));$('#combo').textContent=s.combo>1?`SURGE ×${s.combo}`:'';$('#hull').innerHTML=Array.from({length:s.maxHp},(_,i)=>`<i class="${i>=s.hp?'empty':''}"></i>`).join('')+(s.shield?'<i style="background:#75fff1;box-shadow:0 0 8px #75fff1"></i>':'');$('#boss-hud').classList.toggle('hidden',!s.boss);if(s.boss){const life=Math.round(s.boss.hp*100);$('#boss-name').textContent=s.boss.shield?`${s.boss.name} // SHIELDED`:s.boss.name;$('#boss-life').style.transform=`scaleX(${s.boss.hp})`;$('#boss-meter').setAttribute('aria-valuenow',String(life))}},
 upgrade(items,levels){const box=$('#cards');box.replaceChildren();for(const item of items){const b=document.createElement('button');b.className=`card ${item.rare?'rare':''}`;b.innerHTML=`<i>${item.icon}</i><span><strong>${item.name}</strong><small>${item.text}</small></span><span>LV.${(levels[item.id]||0)+1}</span>`;b.addEventListener('click',()=>{if(game.choose(item.id))vibrate(15)},{once:true});box.append(b)}},
 result(r){const old=data.best;data=recordRun(data,r);persist();$('#result-kicker').textContent=r.victory?'STAR REKINDLED':'THREAD LOST';$('#result-title').textContent=r.victory?'DAWN RESTORED':'RUN OVER';$('#result-copy').textContent=r.victory?`光の糸で${r.kills}体を切り、死んだ星を再点火した。`:(r.wave>=5?'最終光路は近い。次は勢いを切らすな。':'重力点を動かし、敵を糸の間へ通せ。');$('#result-score').textContent=formatNumber(r.score);$('#result-wave').textContent=`${r.wave} / 8`;$('#result-combo').textContent=r.maxCombo;$('#result-time').textContent=formatTime(r.time);$('#record').classList.toggle('hidden',r.score<=old);$('#again').textContent=r.victory?'新しい航路へ':'もう一度';show('result');hudVisible(false);vibrate(r.victory?[35,35,35,35,75]:[55,35,85])},
 toast,quality(level){toast(level===1?'描画負荷を自動調整しました':'省電力描画に切り替えました')}
}});
function records(){$('#best').textContent=formatNumber(data.best);$('#depth').textContent=data.depth?`${data.depth}/8`:'—';$('#wins').textContent=data.wins;$('#sound').checked=data.settings.sound;$('#vibration').checked=data.settings.vibration;$('#reduced').checked=data.settings.reduced;document.documentElement.classList.toggle('reduce-motion',data.settings.reduced)}
function randomSeed(){return(globalThis.crypto?.getRandomValues?.(new Uint32Array(1))[0]||Date.now())>>>0}
async function requestStart(){await sound.unlock();vibrate(10);if(!data.tutorial){tutorialStep=0;renderTutorial();show('tutorial')}else start()}
function start(reuse=false){void sound.unlock();run={seed:reuse?run.seed:randomSeed()};show('');hudVisible(true);game.start(run)}
function menu(){game.stop();records();hudVisible(false);show('menu')}
const tutorial=[['01 / 03','重力を置く','画面を押すと指先に重力点が生まれ、機体が引かれます。'],['02 / 03','光の糸で切る','機体と指先を結ぶ光の糸に敵を通してください。速いほど威力が上がります。'],['03 / 03','離して飛ぶ','指を離すと勢いを保って滑空。次の重力点で軌道を曲げ、全8区画を突破します。']];
function renderTutorial(){const t=tutorial[tutorialStep];$('#tutorial-count').textContent=t[0];$('#tutorial-title').textContent=t[1];$('#tutorial-copy').textContent=t[2];$('#tutorial-next').textContent=tutorialStep===2?'開始':'次へ'}
function finishTutorial(){data.tutorial=true;persist();start()}
$('#start').addEventListener('click',requestStart);$('#pause').addEventListener('click',()=>game.pause());$('#resume').addEventListener('click',async()=>{await sound.unlock();game.resume()});$('#retry').addEventListener('click',()=>start(true));$('#quit').addEventListener('click',menu);$('#again').addEventListener('click',()=>start(false));$('#result-menu').addEventListener('click',menu);
$('#tutorial-next').addEventListener('click',()=>{sound.event('ui');if(tutorialStep<2){tutorialStep++;renderTutorial()}else finishTutorial()});$('#tutorial-skip').addEventListener('click',finishTutorial);
$('#help').addEventListener('click',()=>show('help-panel'));$('#settings').addEventListener('click',()=>show('settings-panel'));for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>show('menu'));
$('#sound').addEventListener('change',async e=>{data.settings.sound=e.target.checked;persist();sound.setEnabled(e.target.checked);if(e.target.checked){await sound.unlock();sound.event('ui')}});$('#vibration').addEventListener('change',e=>{data.settings.vibration=e.target.checked;persist();vibrate(15)});$('#reduced').addEventListener('change',e=>{data.settings.reduced=e.target.checked;persist()});
$('#reset').addEventListener('click',e=>{const b=e.currentTarget;if(!b.dataset.ready){b.dataset.ready='1';b.textContent='もう一度押すと記録を消去';clearTimeout(resetTimer);resetTimer=setTimeout(()=>{delete b.dataset.ready;b.textContent='記録をリセット'},3500);return}clearTimeout(resetTimer);data=reset();persist();sound.setEnabled(data.settings.sound);delete b.dataset.ready;b.textContent='記録をリセット';toast('記録をリセットしました')});
document.addEventListener('visibilitychange',()=>{if(document.hidden)game.pause('visibility')});globalThis.addEventListener('pagehide',()=>game.pause('pagehide'));globalThis.addEventListener('blur',()=>game.cancelPointer());document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('dblclick',e=>{if(e.target===canvas)e.preventDefault()},{passive:false});
globalThis.addEventListener('error',e=>{console.error(e.error||e.message);if(game.state?.status==='running'){game.pause('error');toast('一時停止しました。再開できない場合はページを再読み込みしてください。',4000)}});globalThis.addEventListener('unhandledrejection',e=>console.error(e.reason));
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))globalThis.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('offline unavailable',e)));
const local=['localhost','127.0.0.1','[::1]'].includes(location.hostname)&&new URLSearchParams(location.search).get('test')==='1';if(local)Object.defineProperty(globalThis,'__Q_TEST__',{value:Object.freeze({start:seed=>game.start({seed:seed||12345}),snapshot:()=>game.testSnapshot(),wave:n=>game.testWave(n),clearWave:()=>game.testClearWave(),finish:v=>game.finish(Boolean(v)),pause:reason=>game.pause(reason||'test'),resume:()=>game.resume(),particles:n=>game.testParticles(n),clear:()=>{data=reset();records()}})});
records();hudVisible(false);show('menu');
