import * as T from 'three';
import { bakeStaticTransforms } from './static-transforms.js';
import { gatheringStage } from './gathering-presentation.js';
import { GatheringScene } from './gathering-scene.js';
import { ExpeditionScene } from './expedition-scene.js';
import { SALT_REACH } from './world-regions.js';
import { VillageScene } from './village-scene.js';
import { loadCharacterAssets } from './character-assets.js';
import { createRiggedActor } from './rigged-actor.js';
import { cameraFraction } from './spatial.js';
import { WEAPONS, SENA, EAST_CAMP } from './content.js';
import { PLACES, BRIDGES, groundAt, heightAt, random, WORLD_SEED, clamp, distance, riverX, inWater } from './core.js';

const C = { stone:0x697b78, dark:0x293a40, gold:0xcdb57a, wood:0x514840, leaf:0x566c53 };
const box = new T.BoxGeometry(1,1,1), sphere = new T.IcosahedronGeometry(1,1), cone = new T.ConeGeometry(1,1,7), cylinder = new T.CylinderGeometry(1,1,1,8);
const mats = new Map();
function material(color,extra={}) {const key=String(color)+JSON.stringify(extra);if(!mats.has(key))mats.set(key,new T.MeshStandardMaterial({color,roughness:.88,...extra}));return mats.get(key);}
function mesh(geometry,mat,parent,pos=[0,0,0],scale=[1,1,1],shadow=false){const m=new T.Mesh(geometry,mat);m.position.set(...pos);m.scale.set(...scale);m.castShadow=shadow;m.receiveShadow=true;parent.add(m);return m;}
function addBox(parent,color,x,y,z,sx,sy,sz,shadow=false){return mesh(box,material(color),parent,[x,y,z],[sx,sy,sz],shadow);}

function humanoid(type='player'){
  const g=new T.Group(),body=new T.Group();g.add(body);const player=type==='player',boss=type==='boss',ranger=type==='ranger',npc=!player&&!boss&&!ranger;
  const armor=material(player?0x788e94:npc?0x797565:boss?0x26383c:ranger?0x8a735a:0x596569,{metalness:.35,roughness:.52});
  const cloth=material(player?0x3c6268:npc?0xb29569:boss?0x262d36:0x51484a);const leather=material(0x303f41);const gold=material(C.gold,{metalness:.65,roughness:.35});
  mesh(sphere,armor,body,[0,1.18,0],[.34,.46,.23],true);
  mesh(cylinder,leather,body,[0,.87,0],[.28,.22,.22],true);
  const head=mesh(sphere,armor,body,[0,1.86,0],[.235,.28,.23],true);
  mesh(box,material(0x171f23),head,[0,0,.86],[1.3,.25,.2]);
  mesh(box,material(boss?0xee995e:0xc9d8c7,{emissive:boss?0xba5e2b:0x1f3c3b,emissiveIntensity:1}),head,[0,-.04,.97],[.65,.08,.03]);
  if(player||npc||ranger)mesh(sphere,cloth,body,[0,1.95,-.055],[.265,.3,.245],true);
  if(player)mesh(box,armor,body,[0,1.88,.219],[.26,.06,.04]);
  const arms=[],legs=[];
  for(const side of [-1,1]){
    const a=new T.Group();a.position.set(side*.4,1.49,0);body.add(a);mesh(sphere,armor,a,[0,-.03,0],[.22,.2,.23],true);mesh(cylinder,cloth,a,[0,-.31,0],[.105,.45,.1],true);mesh(sphere,armor,a,[0,-.57,.015],[.12,.22,.12],true);arms.push(a);
    const l=new T.Group();l.position.set(side*.17,.83,0);body.add(l);mesh(cylinder,leather,l,[0,-.23,0],[.115,.52,.12],true);mesh(sphere,armor,l,[0,-.63,.06],[.14,.24,.18],true);legs.push(l);
  }
  const sword=new T.Group();sword.position.set(0,-.65,0);arms[1].add(sword);mesh(box,gold,sword,[0,-.07,0],[.35,.07,.13],true);mesh(box,material(0xced8d4,{metalness:.75,roughness:.25}),sword,[0,-.73,.02],[.09,1.2,.055],true);mesh(cone,gold,sword,[0,-1.4,.02],[.07,.22,.05]);
  const capeGeo=new T.PlaneGeometry(.95,1.35,5,7);const cape=mesh(capeGeo,new T.MeshStandardMaterial({color:player?0x4c7473:boss?0x354149:0x766b5e,side:T.DoubleSide,roughness:1}),body,[0,1.15,-.27]);cape.rotation.x=-.13;cape.userData.base=Float32Array.from(capeGeo.attributes.position.array);
  if(boss){for(const s of [-1,1]){const horn=mesh(cone,gold,body,[s*.29,2.25,0],[.08,.8,.1],true);horn.rotation.z=-s*.45;mesh(cone,gold,body,[s*.45,2.44,0],[.045,.34,.06],true);}g.scale.setScalar(2.3);}
  if(npc)sword.visible=false;
  if(type==='smith'){mesh(box,material(0x6c4732),body,[0,1.03,.245],[.52,.8,.04]);mesh(cylinder,material(C.wood),arms[1],[0,-.7,0],[.04,.6,.04]);mesh(box,material(C.stone),arms[1],[0,-1,0],[.34,.18,.18]);}
  if(type==='healer'){mesh(cylinder,material(0x887651),body,[0,1,-.43],[.3,.6,.25]);for(const side of [-1,1])mesh(cone,material(0x7caa91),body,[side*.13,1.48,-.44],[.13,.6,.08]);}
  if(['porter','traveler','courier'].includes(type)){const pack=mesh(box,material(type==='courier'?0x8b7654:0x75654e),body,[0,1.2,-.38],[.43,.52,.25],true);for(const side of [-1,1])addBox(pack,0xc4b48a,side*.22,.05,.26,.05,.72,.05);}
  if(type==='patient')g.scale.setScalar(.94);
  if(type==='scout'){mesh(cylinder,material(0x586d62),body,[0,1.18,-.38],[.3,.62,.22]);mesh(cylinder,material(C.wood),arms[1],[0,-.8,0],[.035,1.5,.035]);}
  if(type==='npc'){sword.visible=false;mesh(cylinder,gold,arms[1],[0,-.6,0],[.04,1.8,.04]);mesh(sphere,material(0xffdb93,{emissive:0xf7ad48,emissiveIntensity:2}),arms[1],[0,.35,0],[.14,.19,.14]);}
  let spear=null,flask=null;
  if(player){spear=new T.Group();spear.position.set(0,-.6,0);arms[1].add(spear);mesh(cylinder,material(0x4b3f31),spear,[0,-.4,0],[.035,2.7,.035],true);mesh(cone,material(0xc8d9d0,{metalness:.7,roughness:.3}),spear,[0,-1.95,0],[.11,.45,.11],true).rotation.z=Math.PI;spear.visible=false;}
  if(player){flask=new T.Group();flask.position.set(0,-.72,.06);arms[1].add(flask);mesh(sphere,material(0x84bca0,{metalness:.25,roughness:.3,emissive:0x254539,emissiveIntensity:.5}),flask,[0,0,0],[.12,.17,.12],true);mesh(cylinder,gold,flask,[0,.18,0],[.05,.1,.05]);flask.visible=false;}
  if(ranger){sword.visible=false;const bow=new T.Group();arms[0].add(bow);bow.position.set(0,-.5,.25);mesh(new T.TorusGeometry(.5,.035,5,16,Math.PI),material(0xa99469),bow).rotation.z=-Math.PI/2;const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(0,-.5,0),new T.Vector3(0,.5,0)]),new T.LineBasicMaterial({color:0xd7cbb4}));bow.add(line);}
  return {g,body,arms,legs,sword,spear,flask,cape,type};
}
function wolf(){const g=new T.Group(),body=new T.Group();g.add(body);const fur=material(0x5e6867);mesh(sphere,fur,body,[0,.65,0],[.36,.36,.64],true);mesh(sphere,fur,body,[0,.89,.66],[.29,.32,.38],true);mesh(sphere,material(0x34444a),body,[0,.83,.95],[.16,.15,.24],true);for(const s of [-1,1]){mesh(cone,fur,body,[s*.19,1.23,.65],[.12,.25,.12],true);mesh(sphere,material(0xe8b061,{emissive:0xe28439,emissiveIntensity:1}),body,[s*.21,.97,.9],[.045,.045,.045]);}const legs=[];for(const x of [-.25,.25])for(const z of [-.44,.44]){const l=new T.Group();l.position.set(x,.63,z);body.add(l);mesh(cylinder,fur,l,[0,-.23,0],[.075,.48,.085],true);legs.push(l);}const tail=mesh(cone,fur,body,[0,.65,-.88],[.15,.64,.15]);tail.rotation.x=-1.8;return{g,body,legs,type:'wolf'};}

export async function createSceneView(canvas,game,settings){
  return new SceneView(canvas,game,settings,await loadCharacterAssets());
}

export class SceneView {
  constructor(canvas,game,settings,characters){
    this.canvas=canvas;this.game=game;this.settings=settings;this.scene=new T.Scene();this.scene.background=new T.Color(0x9aacac);this.scene.fog=new T.FogExp2(0x9bacac,.0042);
    this.camera=new T.PerspectiveCamera(54,innerWidth/innerHeight,.1,1100);this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='high'?1.7:settings.quality==='low'?1:1.35));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.enabled=settings.quality!=='low';this.renderer.shadowMap.type=T.PCFSoftShadowMap;
    this.ambient=new T.HemisphereLight(0xc6dfe0,0x526552,2.1);this.scene.add(this.ambient);this.sun=new T.DirectionalLight(0xffddaa,3);this.sun.position.set(-80,100,-70);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35,near:1,far:220});this.sun.shadow.bias=-.0008;this.sun.shadow.normalBias=.04;this.scene.add(this.sun,this.sun.target);
    this.rng=random(WORLD_SEED);this.t=0;this.yaw=.06;this.gatheringFocus=null;this.pitch=.3;this.zoom=9;this.shake=0;this.effects=[];this.enemyModels=new Map();this.beacons=new Map();this.lootModels=new Map();this.sway={value:0};
    this.createSky();
    for(const method of ['createTerrain','createMountains','createVegetation','createWater'])this.createStaticScenery(method);
    this.createStructures();this.createStaticScenery('createCrossing');this.createParticles();
    this.player=createRiggedActor(characters,'player');this.scene.add(this.player.g);this.npc=createRiggedActor(characters,'npc');this.npc.g.position.set(7,heightAt(7,80),80);this.npc.g.rotation.y=1.4;this.scene.add(this.npc.g);this.sena=createRiggedActor(characters,'npc');this.sena.g.position.set(SENA.x,heightAt(SENA.x,SENA.z),SENA.z);this.sena.g.rotation.y=-1.5;this.scene.add(this.sena.g);
    this.residentModels=new Map();for(const n of game.residents){const model=humanoid(n.role);this.residentModels.set(n.id,model);this.scene.add(model.g);}
    this.village=new VillageScene(this.scene,this.player);this.expeditionScene=new ExpeditionScene(this.scene,groundAt);this.expeditionScene.update(game);this.gatheringScene=new GatheringScene(this.scene,groundAt);this.gatheringScene.update(game);
    this.telegraphRing=new T.RingGeometry(.7,1,32);this.telegraphArc=new T.RingGeometry(.04,1,32,1,-Math.PI/2-1.5,3);
    for(const e of game.enemies){const m=e.type==='wolf'?wolf():e.type==='knight'?createRiggedActor(characters,'soldier'):humanoid(e.type);this.scene.add(m.g);this.enemyModels.set(e.id,m);const ringGeo=this.telegraphArc;m.telegraph=mesh(ringGeo,new T.MeshBasicMaterial({color:0xf39855,transparent:true,opacity:.5,side:T.DoubleSide,depthWrite:false}),this.scene);m.telegraph.rotation.x=-Math.PI/2;m.telegraph.visible=false;if(e.type==='ranger'){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute([0,0,0,0,0,0],3));m.aimLine=new T.Line(geo,new T.LineBasicMaterial({color:0xf1af75,transparent:true,opacity:.65}));m.aimLine.visible=false;this.scene.add(m.aimLine);}}
    for(const item of game.pickups){const g=new T.Group();g.position.set(item.x,heightAt(item.x,item.z),item.z);if(item.type==='chest'||item.type==='supplies'){addBox(g,0x584c3a,0,.35,0,1.2,.65,.72,true);for(const x of [-.4,.4])addBox(g,C.gold,x,.4,0,.08,.72,.76);addBox(g,C.gold,0,.4,.39,.18,.18,.06);}else{for(let i=0;i<3;i++){const leaf=mesh(cone,material(item.type==='relic'?0xa7cab7:0x7caa91,{emissive:item.type==='relic'?0x7dc9a2:0x234831,emissiveIntensity:.7}),g,[(i-1)*.17,.42,0],[.17,.85,.09]);leaf.rotation.z=(i-1)*.4;}mesh(sphere,material(0xcee5bc,{emissive:0xb4dca1,emissiveIntensity:1}),g,[0,.8,0],[.075,.075,.075]);}this.scene.add(g);this.lootModels.set(item.id,g);}
    this.arrowShafts=new T.InstancedMesh(new T.BoxGeometry(.045,.045,1.1),material(0xbf9256,{emissive:0x362015}),48);const tips=new T.ConeGeometry(.1,.28,5);tips.rotateX(Math.PI/2);tips.translate(0,0,.65);this.arrowTips=new T.InstancedMesh(tips,material(0xe1bc79),48);this.arrowShafts.count=this.arrowTips.count=0;this.scene.add(this.arrowShafts,this.arrowTips);this.arrowDummy=new T.Object3D();
    this.slash=mesh(new T.RingGeometry(1.4,2.6,36,1,0,Math.PI*1.4),new T.MeshBasicMaterial({color:0xffe4ae,transparent:true,opacity:.65,side:T.DoubleSide,depthWrite:false}),this.scene);this.slash.rotation.x=-Math.PI/2;this.slash.visible=false;
    this.resize=()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);};addEventListener('resize',this.resize);this.setQuality(settings.quality);
  }
  // Only these construction methods contain immutable local transforms. Do not
  // include sky/clouds, actors, loot, effects, beacon animations or quest scenes.
  createStaticScenery(method){const first=this.scene.children.length;this[method]();bakeStaticTransforms(...this.scene.children.slice(first));}
  createSky(){const skyGeo=new T.SphereGeometry(850,24,12);this.skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color(0x50747e)},bottom:{value:new T.Color(0xd0caae)}},vertexShader:'varying vec3 vPosition; void main(){vPosition=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vPosition;void main(){float h=normalize(vPosition).y;gl_FragColor=vec4(mix(bottom,top,pow(max(h,0.),.6)),1.);}'});mesh(skyGeo,this.skyMaterial,this.scene);
    this.sunDisc=mesh(new T.SphereGeometry(1,16,12),new T.MeshBasicMaterial({color:0xffeac0}),this.scene,[-270,190,-450],[19,19,19]);
    const ring=mesh(new T.TorusGeometry(20,.55,5,70),material(0xe6c98c,{emissive:0x8a7445,emissiveIntensity:.4}),this.scene,[4,65,-268]);ring.rotation.y=.05;this.crownHalo=ring;
    const cloudMat=new T.MeshBasicMaterial({color:0xe5dfcd,transparent:true,opacity:.11,depthWrite:false});this.clouds=[];for(let i=0;i<14;i++){const c=mesh(sphere,cloudMat,this.scene,[(this.rng()-.5)*900,90+this.rng()*90,(this.rng()-.5)*850],[40+this.rng()*60,3+this.rng()*5,16+this.rng()*15]);this.clouds.push(c);}
  }
  createTerrain(){for(const [width,offset,segments] of [[660,0,200],[180,-420,55]]){const geo=new T.PlaneGeometry(width,660,segments,200);geo.rotateX(-Math.PI/2);geo.translate(offset,0,0);const pos=geo.attributes.position,colors=[];const color=new T.Color();for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,heightAt(x,z));const path=Math.abs(x-7*Math.sin(z*.035))<3.8;const grove=Math.hypot(x+104,z)<76;const north=z< -125;const h=heightAt(x,z);color.set(path?0xa89c75:grove?0x7b8258:north?0x647671:0x879274);if(h>25)color.set(0x838d87);if(Math.abs(x-riverX(z))<14)color.set(0x818e7f);if(x<SALT_REACH.edgeX)color.lerp(new T.Color(0xb8ad8e),clamp((-x-260)/45,0,1));const shade=.92+.13*Math.sin(x*.19+z*.07)*Math.cos(z*.13);color.multiplyScalar(shade);colors.push(color.r,color.g,color.b);}geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeVertexNormals();mesh(geo,new T.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:false}),this.scene);}}
  createMountains(){const rng=this.rng;for(let i=0;i<30;i++){const angle=i/30*Math.PI*2;const rawX=Math.cos(angle)*(360+rng()*130),x=rawX< -300?rawX-200:rawX,z=Math.sin(angle)*(400+rng()*100);const m=mesh(new T.ConeGeometry(1,1,5+rng()*3|0,3),material(i%2?0x657d82:0x718989),this.scene,[x,38,z],[65+rng()*80,100+rng()*130,65+rng()*50]);m.rotation.y=rng()*7;const cap=mesh(cone,material(0xb5c6c5),this.scene,[x,m.scale.y*.34+38,z],[m.scale.x*.26,m.scale.y*.29,m.scale.z*.26]);cap.rotation.y=m.rotation.y;}}
  createVegetation(){const rng=this.rng,dummy=new T.Object3D(),treePositions=this.game.trees;
    const trunks=new T.InstancedMesh(new T.CylinderGeometry(.12,.22,1,5),material(0x59625a),treePositions.length);const pine=new T.InstancedMesh(new T.ConeGeometry(1,1,7),material(0x47675d),treePositions.length*2);const crowns=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),material(0xbdad6d),treePositions.length);let pi=0,ci=0;treePositions.forEach((p,i)=>{const y=heightAt(p.x,p.z);dummy.position.set(p.x,y+p.h*.38,p.z);dummy.scale.set(1,p.h*.76,1);dummy.rotation.set(0,0,0);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);if(p.gold){dummy.position.y=y+p.h*.75;dummy.scale.set(p.h*.34,p.h*.4,p.h*.34);dummy.rotation.y=rng()*6;dummy.updateMatrix();crowns.setMatrixAt(ci,dummy.matrix);crowns.setColorAt(ci,new T.Color().setHSL(.105+rng()*.04,.25+rng()*.25,.37+rng()*.16));ci++;}else{for(let j=0;j<2;j++){dummy.position.y=y+p.h*(.52+j*.2);dummy.scale.set(p.h*(.37-j*.09),p.h*.73,p.h*(.37-j*.09));dummy.updateMatrix();pine.setMatrixAt(pi++,dummy.matrix);}}});pine.count=pi;crowns.count=ci;this.scene.add(trunks,pine,crowns);trunks.castShadow=false;pine.receiveShadow=true;crowns.receiveShadow=true;
    const rockObs=this.game.obstacles.filter(o=>o.type==='rock');const rocks=new T.InstancedMesh(sphere,material(0x6c7a75),rockObs.length);rockObs.forEach((p,i)=>{dummy.position.set(p.x,heightAt(p.x,p.z)+p.r*.33,p.z);dummy.scale.set(p.r,p.r*.88,p.r);dummy.rotation.set(rng(),rng()*6,rng()*.5);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);});rocks.receiveShadow=true;this.scene.add(rocks);
    const grassGeo=new T.BufferGeometry();grassGeo.setAttribute('position',new T.Float32BufferAttribute([-.12,0,0,.12,0,0,.03,.65,.06],3));grassGeo.computeVertexNormals();const grassMat=new T.MeshStandardMaterial({color:0xb3b48c,side:T.DoubleSide,roughness:1});grassMat.onBeforeCompile=s=>{s.uniforms.uTime=this.sway;s.vertexShader='uniform float uTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(uTime*1.7+instanceMatrix[3].x*.8+instanceMatrix[3].z*.8)*.14*position.y;');};const count=15000;const grass=new T.InstancedMesh(grassGeo,grassMat,count);let gi=0;for(let i=0;i<count;i++){const x=(rng()-.5)*420,z=155-rng()*420;if(inWater(x,z)||PLACES.some(p=>distance({x,z},p)<9)||Math.abs(x)<4)continue;dummy.position.set(x,heightAt(x,z),z);dummy.rotation.set(0,rng()*6,0);const size=.6+rng()*1.1;dummy.scale.set(size,size,size);dummy.updateMatrix();grass.setMatrixAt(gi,dummy.matrix);grass.setColorAt(gi,new T.Color().setHSL(.12+rng()*.045,.2,.43+rng()*.15));gi++;}grass.count=gi;this.grass=grass;this.grassCapacity=gi;this.scene.add(grass);
  }
  createWater(){const geo=new T.PlaneGeometry(21,440,8,100);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const z=pos.getZ(i);pos.setX(i,pos.getX(i)+riverX(z));pos.setY(i,heightAt(riverX(z),z)+.35);}geo.computeVertexNormals();this.waterMat=new T.MeshStandardMaterial({color:0x639394,roughness:.21,metalness:.45,transparent:true,opacity:.88});this.waterMat.onBeforeCompile=s=>{s.uniforms.uTime=this.sway;s.vertexShader='uniform float uTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.y += sin(position.z*.7+uTime)*.09+sin(position.x*1.1+uTime*.8)*.06;');};mesh(geo,this.waterMat,this.scene);for(const b of BRIDGES){
      const {x,z,top}=b;addBox(this.scene,0x7b7360,x,top-.18,z,27,.36,5.3);
      for(let i=-12;i<=12;i+=4)for(const side of [-1,1])addBox(this.scene,C.wood,x+i,top+.75,z+side*2.8,.15,1.65,.15);
      for(const side of [-1,1]){addBox(this.scene,C.wood,x,top+1.4,z+side*2.8,27,.12,.12);const inner=x+side*13.5,outer=x+side*21.5,geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute([inner,top,z-2.65,inner,top,z+2.65,outer,heightAt(outer,z-2.65)+.015,z-2.65,outer,heightAt(outer,z+2.65)+.015,z+2.65],3));geo.setIndex([0,1,2,2,1,3]);geo.computeVertexNormals();mesh(geo,material(0x7b7360,{side:T.DoubleSide}),this.scene);}
    }
  }

  createStructures(){for(const o of this.game.obstacles.filter(o=>o.type==='house')){const g=new T.Group();g.position.set(o.x,heightAt(o.x,o.z),o.z);this.scene.add(g);addBox(g,0x9b9d85,0,1.75,0,5.7,3.5,4.8,true);for(const x of [-2.9,2.9])for(const z of [-2.45,2.45])addBox(g,C.wood,x,1.7,z,.2,3.7,.2);const roof=mesh(new T.ConeGeometry(1,1,4),material(0x4c6365),g,[0,4.4,0],[4.8,2.1,4.1],true);roof.rotation.y=Math.PI/4;addBox(g,0x3b443d,0,.95,2.42,1.3,1.9,.08);for(const x of [-1.8,1.8])addBox(g,0xd2a56e,x,1.9,2.44,.64,.75,.07);addBox(g,C.stone,1.8,4.5,-1,1,2.9,.9,true);bakeStaticTransforms(g);}
    for(const p of PLACES){const g=new T.Group();g.position.set(p.x,heightAt(p.x,p.z),p.z);this.scene.add(g);const boss=p.type==='boss';mesh(new T.CylinderGeometry(boss?10:3.4,boss?11:3.8,.5,12),material(C.stone),g,[0,.2,0]);mesh(new T.CylinderGeometry(1.1,1.35,.75,8),material(0x536460),g,[0,.68,0]);const flame=mesh(new T.IcosahedronGeometry(1,1),new T.MeshStandardMaterial({color:0xf3d28a,emissive:0xffb340,emissiveIntensity:2,transparent:true,opacity:.95}),g,[0,1.55,0],[.24,.76,.24]);const glow=new T.PointLight(0xf7c17b,6,13,2);glow.position.y=2;g.add(glow);const ring=mesh(new T.TorusGeometry(1.4,.027,4,36),material(C.gold,{emissive:0xc79c4e,emissiveIntensity:.8}),g,[0,1.8,0]);const beam=mesh(new T.CylinderGeometry(.045,.28,28,8,1,true),new T.MeshBasicMaterial({color:0xf8dca0,transparent:true,opacity:.12,side:T.DoubleSide,depthWrite:false}),g,[0,15,0]);this.beacons.set(p.id,{g,flame,glow,ring,beam});
      if(p.type!=='camp'){
        const n=boss?10:6,r=boss?13:7;for(let i=0;i<n;i++){const a=i/n*Math.PI*2,x=Math.cos(a)*r,z=Math.sin(a)*r,h=boss?14:(i%3===0?7:4.4);addBox(g,C.stone,x,h/2,z,1.35,h,1.35,true);addBox(g,0x7e8980,x,h+.3,z,1.8,.6,1.8);if(i%2===0)mesh(new T.ConeGeometry(.6,2,4),material(C.dark),g,[x,h+1.7,z]);}
        const arch=new T.Mesh(new T.TorusGeometry(boss?9:5,boss?.95:.65,5,24,Math.PI),material(C.stone));arch.position.set(0,boss?13:6,-(boss?9:5));arch.rotation.z=0;g.add(arch);for(const side of [-1,1])addBox(g,C.stone,side*(boss?9:5),boss?6.5:3,-(boss?9:5),boss?1.9:1.3,boss?13:6,1.7,true);
        if(p.id==='ruins'){const tower=mesh(new T.CylinderGeometry(4,5,17,8,1,true),material(0x667a79),g,[-13,8,-9]);mesh(new T.TorusGeometry(4.3,.4,4,8),material(C.gold),g,[-13,16.4,-9]).rotation.x=Math.PI/2;for(let j=0;j<5;j++)addBox(g,C.dark,-13+Math.sin(j*1.26)*4.1,12,-9+Math.cos(j*1.26)*4.1,.5,2.1,.4);}
      }
      // The beacon group stays mutable; bake only its stonework, not its live
      // flame, light, rotating ring or beam. Their exact hierarchy is retained.
      bakeStaticTransforms(...g.children.filter(child=>![flame,glow,ring,beam].includes(child)));
    }
    // Cloth trail markers make the northern route readable from ground level.
    for(const z of [60,10,-45,-107,-196]){const x=-6+Math.sin(z*.035)*7,y=heightAt(x,z);addBox(this.scene,C.wood,x,y+2,z,.12,4,.12);const flag=mesh(new T.PlaneGeometry(1.3,.85,3,2),material(0xbeb28b,{side:T.DoubleSide}),this.scene,[x+.67,y+3.4,z]);flag.rotation.y=.25;}
  }
  createCrossing(){
    const camp=new T.Group();camp.position.set(EAST_CAMP.x,heightAt(EAST_CAMP.x,EAST_CAMP.z),EAST_CAMP.z);this.scene.add(camp);
    const cart=new T.Group();cart.position.set(3,0,1);cart.rotation.y=-.3;camp.add(cart);addBox(cart,0x635341,0,.85,0,2.4,.3,3.6);for(const x of [-1.15,1.15]){addBox(cart,0x83765b,x,1.25,0,.15,.8,3.7);for(const z of [-1.1,1.1]){const wheel=mesh(new T.TorusGeometry(.6,.12,5,12),material(0x453f31),cart,[x*1.12,.58,z]);wheel.rotation.y=Math.PI/2;}}for(const x of [-.65,.65])addBox(cart,C.wood,x,.8,2.7,.12,.12,2);
    for(const side of [-1,1]){const tent=mesh(new T.ConeGeometry(2.2,2.5,4,1,true),material(side<0?0x7c7354:0x665443,{side:T.DoubleSide}),camp,[side*8,1.2,-7]);tent.rotation.y=Math.PI/4;addBox(camp,C.wood,side*8,1.5,-7,.13,3,.13);}
    this.roadCamp=new T.Group();this.roadCamp.position.set(SENA.x-7,heightAt(SENA.x-7,SENA.z+7),SENA.z+7);this.scene.add(this.roadCamp);mesh(new T.ConeGeometry(2.3,2.7,4,1,true),material(0xc4b48a,{side:T.DoubleSide}),this.roadCamp,[0,1.35,0]).rotation.y=Math.PI/4;addBox(this.roadCamp,0x5c6b56,3,.4,1,1,.8,1);mesh(sphere,material(0xf4c67d,{emissive:0xffb242,emissiveIntensity:2}),this.roadCamp,[3,1.25,1],[.15,.3,.15]);
    this.havenSupplies=new T.Group();this.havenSupplies.position.set(9,heightAt(9,78),78);this.scene.add(this.havenSupplies);for(let i=0;i<3;i++)addBox(this.havenSupplies,0x798e66,i*.7,.25,0,.6,.5,.6);mesh(sphere,material(0xabc899),this.havenSupplies,[.7,.75,0],[.4,.23,.25]);
  }
  createParticles(){const rng=this.rng,positions=new Float32Array(300*3);for(let i=0;i<300;i++){positions[i*3]=(rng()-.5)*100;positions[i*3+1]=rng()*16;positions[i*3+2]=(rng()-.5)*100;}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(positions,3));this.motes=new T.Points(geo,new T.PointsMaterial({color:0xf2d49a,size:.085,transparent:true,opacity:.7,depthWrite:false}));this.scene.add(this.motes);}
  effect(type,x,z){const y=heightAt(x,z)+1;if(['skill','beacon','heal','perfect'].includes(type)){const m=mesh(new T.RingGeometry(.5,.7,40),new T.MeshBasicMaterial({color:type==='heal'?0xa1e5bf:0xffd98e,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false}),this.scene,[x,y-.4,z]);m.rotation.x=-Math.PI/2;this.effects.push({m,life:1,total:1,type});}if(['hit','kill','perfect'].includes(type)){const count=type==='kill'?18:8,geo=new T.BufferGeometry(),pos=[],vel=[];for(let i=0;i<count;i++){pos.push(x,y,z);vel.push((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5);}geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));const m=new T.Points(geo,new T.PointsMaterial({color:0xffd8a0,size:.1,transparent:true,depthWrite:false}));this.scene.add(m);this.effects.push({m,life:.65,total:.65,vel});}if(type==='hit')this.shake=.08;if(type==='hurt')this.shake=.2;}
  animateModel(m,e,dt){if(m.animate){m.animate(e,dt);return;}const moving=e.moving||['chase','return'].includes(e.state);const phase=this.t*(m.type==='wolf'?14:10);if(m.legs)m.legs.forEach((l,i)=>{l.rotation.x=moving?Math.sin(phase+i*Math.PI)*.6:Math.sin(this.t+i)*.015;});if(m.arms){m.arms[0].rotation.x=moving?-Math.sin(phase)*.35:0;m.arms[1].rotation.x=moving?Math.sin(phase)*.35:0;m.arms[1].rotation.z=-.1;m.arms[0].rotation.z=.12;if(e.attack>0){const a=1-e.attack/(e.attackDuration||.46);m.arms[1].rotation.x=-1.9+Math.sin(a*Math.PI)*2.2;m.arms[1].rotation.z=-1.8+a*3.6;m.body.rotation.y=Math.sin(a*Math.PI*2)*.5;}else if(e.state==='windup'){m.arms[1].rotation.x=2.6;m.arms[1].rotation.z=-.6;}else if(e.state==='strike'){m.arms[1].rotation.x=-1.5;}else{m.body.rotation.y*=.8;}if(m.type==='ranger'&&e.state==='windup'){m.arms[0].rotation.x=-1.5;m.arms[1].rotation.x=-1.45;m.arms[1].rotation.z=-.75;}if(e.weaponType==='spear'&&e.attack>0){const phase=1-e.attack/(e.attackDuration||.58);m.arms[1].rotation.x=-1.55+Math.sin(phase*Math.PI)*.45;m.arms[1].rotation.z=0;}if(e.parry>0){m.arms[1].rotation.x=-1.9;m.arms[1].rotation.z=-.6;}if(e.healTimer>0){const phase=1-e.healTimer/.9,lift=Math.min(1,phase/.2,(1-phase)/.22);m.arms[1].rotation.x=-2.75*lift;m.arms[1].rotation.z=-.48*lift;m.body.rotation.y=0;}if(m.cape){const a=m.cape.geometry.attributes.position,b=m.cape.userData.base;for(let i=0;i<a.count;i++){const y=b[i*3+1];a.setZ(i,b[i*3+2]+Math.sin(this.t*3+b[i*3]*4+y*3)*.11*(.8-y)+(moving?.16:0));}a.needsUpdate=true;}}
    m.body.position.y=e.dodge>0?.35:Math.sin(phase*2)*.025*(moving?1:.2);m.body.rotation.x=e.dodge>0?-.9:0;
  }
  update(dt,playing){this.t+=dt;this.sway.value=this.t;const p=this.game.player;this.player.g.position.set(p.x,p.y,p.z);const gathering=this.gatheringFocus?gatheringStage(this.game,this.gatheringFocus):null;this.player.g.rotation.y=gathering?.playerAngle??p.angle;this.animateModel(this.player,p,dt);this.animateModel(this.npc,{moving:false},dt);this.animateModel(this.sena,{moving:false},dt);this.roadCamp.visible=this.game.crossingChoice==='road';this.havenSupplies.visible=this.game.crossingChoice==='haven';
    this.village.update(this.game,dt,this.t);this.expeditionScene.update(this.game);this.gatheringScene.update(this.game);
    const activeResidents=new Set(this.game.npcs().map(n=>n.id));for(const n of this.game.residents){const m=this.residentModels.get(n.id);m.g.visible=activeResidents.has(n.id)&&distance(n,p)<90;if(m.g.visible){m.g.position.set(n.x,n.y,n.z);m.g.rotation.y=gathering?.actorAngles[n.id]??n.angle;this.animateModel(m,n,dt);if(!n.moving&&distance(n,p)>=3.7&&n.role==='smith')m.arms[1].rotation.x=-.6-Math.max(0,Math.sin(this.t*3))*1.3;}}
    const night=(Math.sin((this.game.day-.04)*Math.PI*2)+1)/2;const daylight=.25+night*.75;this.ambient.intensity=1+daylight*1.25;this.sun.intensity=daylight*3;this.skyMaterial.uniforms.top.value.set(0x284252).lerp(new T.Color(0x648d98),daylight);this.skyMaterial.uniforms.bottom.value.set(0x697a83).lerp(new T.Color(this.game.ending==='release'?0xcac9b1:0xc3bfa3),daylight);this.scene.fog.color.copy(this.skyMaterial.uniforms.bottom.value);this.sun.position.set(p.x-75,p.y+100,p.z-50);this.sun.target.position.set(p.x,p.y,p.z);
    for(const e of this.game.enemies){const m=this.enemyModels.get(e.id);m.g.visible=!e.dead&&distance(e,p)<105;if(m.g.visible){m.g.position.set(e.x,e.y,e.z);m.g.rotation.y=e.angle;this.animateModel(m,e,dt);if(!m.animate)m.body.rotation.z=e.state==='stagger'?Math.sin(this.t*35)*.06:0;}m.telegraph.visible=m.g.visible&&e.type!=='ranger'&&['windup','strike'].includes(e.state);if(m.telegraph.visible){const r=e.type==='boss'?(e.radial?9:6.5):e.type==='wolf'?2.5:3.3;m.telegraph.geometry=e.radial?this.telegraphRing:this.telegraphArc;m.telegraph.rotation.set(-Math.PI/2,0,e.angle);m.telegraph.position.set(e.x,e.y+.1,e.z);m.telegraph.scale.setScalar(r);m.telegraph.material.opacity=e.state==='strike'?.8:.13+(1-e.timer/e.windupMax)*.5;}if(m.aimLine){m.aimLine.visible=m.g.visible&&e.state==='windup'&&!!e.aim;if(m.aimLine.visible){const points=m.aimLine.geometry.attributes.position;points.setXYZ(0,e.x,e.y+1.45,e.z);points.setXYZ(1,e.aim.x,e.aim.y,e.aim.z);points.needsUpdate=true;m.aimLine.geometry.computeBoundingSphere();}}}
    const arrows=this.game.projectiles;this.arrowShafts.count=this.arrowTips.count=arrows.length;
    arrows.forEach((a,i)=>{const dummy=this.arrowDummy;dummy.position.set(a.x,a.y,a.z);dummy.lookAt(a.x+a.vx,a.y+a.vy,a.z+a.vz);dummy.updateMatrix();this.arrowShafts.setMatrixAt(i,dummy.matrix);this.arrowTips.setMatrixAt(i,dummy.matrix);this.arrowTips.setColorAt(i,new T.Color(a.owner==='player'?0x8ffff0:0xffbe76));});this.arrowShafts.instanceMatrix.needsUpdate=true;this.arrowTips.instanceMatrix.needsUpdate=true;if(this.arrowTips.instanceColor)this.arrowTips.instanceColor.needsUpdate=true;this.arrowShafts.computeBoundingSphere();this.arrowTips.computeBoundingSphere();
    for(const item of this.game.pickups)this.lootModels.get(item.id).visible=!item.taken&&distance(item,p)<70;
    for(const [id,b]of this.beacons){const lit=this.game.lit.includes(id)||(id==='crown'&&this.game.bossDefeated);b.flame.visible=lit;b.glow.visible=lit;b.flame.rotation.y=this.t;b.flame.scale.y=.6+Math.sin(this.t*5)*.1;b.beam.visible=lit;b.ring.rotation.y=this.t*.35;b.ring.material.emissiveIntensity=lit?1:.1;}
    this.crownHalo.rotation.z=Math.sin(this.t*.06)*.12;
    const stats=WEAPONS[p.weaponType]||WEAPONS.sword;this.slash.visible=p.attack>.05&&p.attack<stats.duration-stats.hitTime+.08;this.slash.scale.setScalar(stats.reach/3.5);if(this.slash.visible){this.slash.position.set(p.x,p.y+1.05,p.z);this.slash.rotation.set(-Math.PI/2,0,-p.angle+this.t*10);this.slash.material.opacity=p.attack*2;}
    this.motes.position.set(p.x,Math.max(0,p.y),p.z);this.motes.rotation.y=this.t*.005;this.motes.position.y+=Math.sin(this.t*.4);this.clouds.forEach((c,i)=>c.position.x+=dt*(.25+i*.01));
    for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;if(e.life<=0){this.scene.remove(e.m);e.m.geometry.dispose();e.m.material.dispose();this.effects.splice(i,1);continue;}e.m.material.opacity=e.life/e.total;if(e.vel){const a=e.m.geometry.attributes.position;for(let j=0;j<a.count;j++){e.vel[j*3+1]-=dt*8;a.setXYZ(j,a.getX(j)+e.vel[j*3]*dt,a.getY(j)+e.vel[j*3+1]*dt,a.getZ(j)+e.vel[j*3+2]*dt);}a.needsUpdate=true;}else e.m.scale.setScalar(1+(1-e.life/e.total)*(e.type==='skill'?13:6));}
    if(playing){const target=gathering?new T.Vector3(gathering.target.x,groundAt(gathering.target.x,gathering.target.z)+1.45,gathering.target.z):new T.Vector3(p.x,p.y+1.6,p.z);const lock=this.game.enemies.find(e=>e.id===this.game.locked);if(!gathering&&lock&&!lock.dead){const yaw=Math.atan2(p.x-lock.x,p.z-lock.z);this.yaw+=Math.atan2(Math.sin(yaw-this.yaw),Math.cos(yaw-this.yaw))*dt*4;target.lerp(new T.Vector3(lock.x,lock.y+1.5,lock.z),.2);}
      const d=this.zoom*(innerHeight>innerWidth?1.12:1);const desired=gathering?new T.Vector3(gathering.camera.x,groundAt(gathering.camera.x,gathering.camera.z)+3.2,gathering.camera.z):new T.Vector3(p.x+Math.sin(this.yaw)*Math.cos(this.pitch)*d,p.y+1.7+Math.sin(this.pitch)*d,p.z+Math.cos(this.yaw)*Math.cos(this.pitch)*d);const fraction=cameraFraction(target,desired,this.game.obstacles,groundAt);desired.lerpVectors(target,desired,fraction);this.camera.position.lerp(desired,this.cameraSnap?1:1-Math.exp(-dt*9));this.cameraSnap=false;const safe=cameraFraction(target,this.camera.position,this.game.obstacles,groundAt);if(safe<1)this.camera.position.lerpVectors(target,this.camera.position,safe);if(this.shake>0){this.shake=Math.max(0,this.shake-dt);this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.y+=(Math.random()-.5)*this.shake;}this.camera.lookAt(target);
    }else{this.camera.position.set(-15+Math.sin(this.t*.025)*3,22,120);this.camera.lookAt(12,6,-48);}
    this.renderer.render(this.scene,this.camera);
  }
  focusGathering(id){this.gatheringFocus=id;this.snapCamera();}
  ringBell(id){this.village.ring(id);}
  snapCamera(){this.cameraSnap=true;this.shake=0;}
  project(x,y,z){const p=new T.Vector3(x,y,z).project(this.camera);return{x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight,visible:p.z<1&&p.z>-1};}
  setQuality(quality){this.settings.quality=quality;this.renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.7:quality==='low'?1:1.35));this.renderer.shadowMap.enabled=quality!=='low';if(this.grass)this.grass.count=Math.min(this.grassCapacity,quality==='low'?4500:quality==='medium'?9000:this.grassCapacity);this.motes?.geometry.setDrawRange(0,quality==='low'?90:quality==='medium'?180:300);this.resize();}
}
