from pathlib import Path
import json
out=Path(__file__).parent
full='/workspace/scratch/e72662e3b71f/Q-mira-cloth-join-v64/docs/evidence/character-reference-v60/references/mira-complete-six-views-v1.png'
corrections=[
('P04',6,'The first image incorrectly shows an entire cowl with a brooch for P04. REMOVE that assembly completely. The replacement is ONE SMALL FOUR-EDGED SADDLE PATCH only, roughly rectangular, wider than tall, with just one smooth shallow double curvature over ONE right shoulder. There is NO neck opening, NO front cowl, NO brooch, NO metal, NO dangling flaps and NO pleats. Four thin raw cut edges are visible, no other garment pieces attached. It joins cowl above to the tops of cape panels below, but those neighbours are ABSENT. Use a small BACK THREE-QUARTER locator that marks only a palm-sized patch on the right shoulder, image right in a rear view. The source cloth texture is NOT ornament: use plain matte cloth.'),
('W02',5,'The first image incorrectly turns W02 into a whole front scarf. Correct it to ONE SMALL SIDE BRIDGE PATCH, a plain crescent-like thin quadrilateral curved over ONLY one shoulder, slightly taller than wide. It has four open cut edges. A single shallow curvature is enough. NO draping across the chest, NO U-shaped scarf, NO nested folds, NO brooch, NO fastening tabs, NO neck ring. Front fold W01 and back fold W03 are not attached and not shown. On a small RIGHT SIDE three-quarter locator, mark only the short bridge on top of the right shoulder between the front and back cowl, not the chest span.'),
('W01',4,'The first W01 incorrectly contains several stacked cowl folds. Replace it with exactly ONE narrow U-shaped folded strip: ONE continuous rolled-over soft ridge from its left end to its right end, the centre sagging below the two ends. There are no second or third ridges and no parallel nested U bands. The strip itself is narrow, NOT the whole front scarf. Show its ONE folded cross-section in TRUE PROFILE. The two ends are freely cut and unattached. Tiny frontal locator marks ONE single narrow stripe across the front cowl, not all cowl layers.'),
('W03',5,'The first W03 incorrectly contains several stacked rear cowl folds. Replace it with exactly ONE narrow shallow V-shaped folded strip: ONE soft rounded ridge from left end down to centre and up to right end. No second or third nested V, no hood, no whole rear cowl. Exactly two free ends, one continuous simple fold. Tiny REAR locator marks ONE narrow V row of the rear cowl, not the entire drape.'),
('L01',6,'The first L01 incorrectly shows TWO front skirt panels together. Replace with exactly ONE right lower-front panel only: one thin elongated flared trapezoidal surface, ONE continuous face, FOUR boundary edges, with a nearly straight inner vertical edge and sloping outer side edge. The whole left panel is absent. There is NO centre split inside this individual panel and no centre seam. It is only half the front of the long tunic, not a complete skirt. Same single panel in all four views. Tiny FRONT locator marks only image LEFT of the split (anatomical right), from belt seam to knee, not both sides and not cape.'),
('L02',6,'The first L02 is too broad and depicts the complete rear skirt width. Replace with exactly ONE rear-right quarter panel only, one thin gently flared trapezoid, taller than wide, with one straight centre-back cut edge and one slightly sloping side cut edge. No centre seam within this panel, no opposite half, no full skirt or circular tube. Four raw open edges. Tiny REAR locator with cape lifted aside marks only image RIGHT half of the rear LOWER TUNIC below belt and above knee; do not colour the cape surface.'),
('C01',4,'The first C01 wraps most of a collar. Replace with exactly ONE FRONT-RIGHT QUARTER collar strip only, approximately a 90-degree arc, thin upright rectangle curved once. Both vertical ends are free, the arc never forms a U or C or closed ring. The front-left quarter and entire back collar are ABSENT. Show the same quarter strip from the convex outside, edge view, concave inside and 3/4. Tiny frontal neckline locator marks only anatomical RIGHT (image LEFT) from centre-front opening to side of neck, NOT the whole front collar.'),
('P03',5,'Keep a single long narrow cape front-opening wedge panel, ONE curved cloth surface with no attached side/rear panels. Correct the locator: it belongs to the OUTER CAPE front edge beside the right arm, from SHOULDER down toward ankle. It is not the knee-length split lower tunic. Use a FRONT three-quarter context showing staff/anatomical right at image LEFT, and highlight only the narrow OUTER CAPE edge from the right shoulder to cape hem on image LEFT. No orange on the central skirt. Preserve one panel and thin raw internal edge; do not enlarge to an entire cape.')]
items=[]
common='''Use case: precise-object-edit. Make one replacement SINGLE-TYPE shape-reference sheet, correcting only the stated physical-part error from reference 1. Discard the other labelled rows entirely. Reference 2 governs only the SAME Mira palette/placement, not the size of the isolated small part. Wide opaque light-grey canvas, no transparency and no vignette. Exactly one isolated object, repeated in OUTER FACE / TRUE PROFILE / INNER FACE / THREE-QUARTER views, plus a small PLACEMENT locator. Large part ID, those view labels, no other text or dimensions. The four views must depict the same object topology. Plain matte muted grey-olive wool; no brocade/spirals/piping/extra thick rims. Raw thin cut edges where divided from neighbours; do not turn an internal cut into decoration. No whole garment in any isolated view. Right=-X, front+Z. The locator is only context. This is visual reference, not precision CAD or a game screenshot.\n'''
for tid,n,detail in corrections:
 prompt=common+'Label exactly "'+tid+'".\n'+detail+'\n'
 path=out/(tid+'-v2-prompt.txt');path.write_text(prompt)
 items.append({'typeID':tid,'prompt':prompt,'promptPath':str(path),'referencePaths':[str(out/f'cloth-{n:02d}-v1.png'),full]})
(out/'CORRECTION-PLAN.json').write_text(json.dumps(items,indent=2)+'\n')
print(json.dumps(items))
