from pathlib import Path
import json
out=Path(__file__).parent
r='/workspace/scratch/e72662e3b71f/Q-mira-cloth-join-v64/docs/evidence/character-reference-v60/references/'
data=[
('TR01','trouser front leg half-shell',['TR01-R','TR01-L'],'TR04 waist; outside and inside seams TR02; upper inner cutout TR03; bottom TR05','ONE front half of ONE right trouser leg from waist to boot-top. A thin long open tapered trough, wider at thigh, narrower at shin, with one gentle knee bend. The entire rear wall and entire other leg are ABSENT. TWO free long edges (inseam and outseam), one short waist-segment edge at top, one smaller half-circular open rim at bottom. Upper inner cut edge curves to meet the separate crotch gusset, but that gusset is not attached. No closed tube, no whole trousers, no two-leg garment. Front outside view and concave inner view of the SAME single wall. Plain dark drab-brown cloth matching trousers under the long tunic, no leather, no boot, no belt. Locator on a small front figure with outer tunic hidden as ghosted context marks ONLY the front of anatomical RIGHT leg (image LEFT), waist to boot top.'),
('TR02','trouser rear leg and seat half-shell',['TR02-R','TR02-L'],'TR04 waist; both side seams TR01; upper inner cutout TR03; bottom TR05','ONE rear half of ONE right trouser leg, from the right half of the seat/waist to boot-top. One thin long tapered open half-shell with a gentle outward seat bulge near top and one gentle knee bend below. Opposite leg and front wall are ABSENT. TWO long exposed free seam edges, open partial waist edge, open semicircular bottom edge. Do not add a crotch bridge: its upper inner cutout awaits separate TR03. Not a complete pair of trousers, no belt, leather or boot. Plain dark drab-brown cloth. Locator uses a REAR view with coat ghosted aside and only the right rear leg (image RIGHT) marked, including right seat but not left buttock.'),
('TR03','crotch gusset saddle',['TR03-C'],'four cut edges to inner top contours of TR01-R/L and TR02-R/L','ONE small diamond-shaped soft saddle patch, the crotch gusset ONLY. Thin dark drab-brown cloth, one shallow saddle bend. FOUR free cut edges. Absolutely no legs, no waistband, no attached front or rear trouser panels, no full underwear or shorts. Wider at centre, tapering to front/back tips; small single curved diamond. Outer and inner are opposite faces of the same patch. Locator is a small neutral garment-only diagrammatic view of trousers with a translucent/ghosted front wall exposing the crotch seam, no anatomy or skin, indicating the single gusset at the junction of inseams.'),
('TR04','trouser waist fabric strip',['TR04-front-R','TR04-front-L','TR04-rear-R','TR04-rear-L'],'lower edge TR01/TR02; four endpoints shared around trouser waist','ONE short quarter-arc CLOTH waistband segment, thin soft dark drab-brown fabric with TWO free short cut ends. This is the under-trouser waistband, NOT the outer brown leather belt B01. No buckle, no leather, no metal, no entire ring, no pants attached. One shallow curve across the strip. Locator marks one quarter of the hidden trousers waist with outer tunic and leather belt ghosted aside, showing fabric clearly distinct from the outer belt.'),
('TR05','trouser boot underlap strip',['TR05-R','TR05-L'],'top TR01/TR02 bottom edges; lower edge tucked inside boot AB07/AB08','ONE thin cloth ankle/boot-entry turnback strip, a short open curved arc with TWO cut ends and a single thin turned-under edge. Plain dark drab-brown cloth, no leather, no metal. Not an entire boot, no boot cuff as the isolated object. Not a closed rigid ring. Locator shows the cloth at the trouser bottom going just INSIDE the top of the boot, with boot upper semi-transparent so cloth underlap is clear; no invented exterior band.'),
('PH01','cape hem turnback segment',['PH01-P01-R','PH01-P01-L','PH01-P02-R','PH01-P02-L','PH01-P03-R','PH01-P03-L'],'upper edge inherits matching cape P01/P02/P03 hem curve; neighbouring endpoints shared, no individual end caps','ONE short cape HEM turnback strip only, a thin gently curved horizontal grey-olive wool band with ONE soft folded cross-section and TWO raw open cut ends. No full cape, no skirt, no lower-tunic hem, no closed ring, no solid end caps. Preserve the subdued cape material. The locator is a small BACK cape view highlighting only ONE short section of the ANKLE-LENGTH outer cape bottom edge, not the knee-length tunic. This type later follows six cape-sector boundaries; do not draw six distinct objects.')]
common='''Use case: stylized-concept. SINGLE-TYPE micro-part reference sheet for Mira, no 3D implementation. Reference 1 gives complete garment identity, reference 2 the clothing layer context; never copy the whole outfit into isolated views. One type only shown in OUTER FACE, TRUE PROFILE, INNER FACE, THREE-QUARTER plus one small PLACEMENT context. Uniform opaque light grey, no vignette. Simple shape with thin physical cut edges, NOT ornamental piping. No text besides type ID and view labels. All four views depict the same topology. Right=-X/Left=+X; front camera gives anatomical right on image left, rear camera on image right. Dimensions and exact seam coordinates belong to an author ledger, not generated text. No extra seams/folds/patterns/embroidery. Keep single-object scale and only one surface or one folded strip.\n'''
items=[]
for tid,name,instances,edge,detail in data:
 prompt=common+'Title exactly "'+tid+'".\n'+detail+'\n'
 path=out/(tid+'-v1-prompt.txt');path.write_text(prompt)
 items.append({'typeID':tid,'name':name,'instances':instances,'boundaryContract':edge,'dimensionStatus':'unmeasured author specification pending; images not CAD','prompt':prompt,'promptPath':str(path),'referencePaths':[r+'mira-complete-six-views-v1.png',r+('mira-cape-views-v2.png' if tid=='PH01' else 'mira-lower-views-v1.png')],'status':'planned-not-submitted','reason':'explicitly missing canonical clothing coverage, not an arbitrary grid subdivision'})
(out/'ADDITIONS-PLAN.json').write_text(json.dumps({'types':items,'typeCount':6,'instanceCount':17,'globalStatus':'proposed scoped additions, old34/79 unchanged'},indent=2)+'\n');print(json.dumps(items))
