#!/usr/bin/env python3
"""Read saved CC0 hm08 triangle sections; compile Mira-only garment contours.
Offline deterministic authoring. No application code, morph, scan or new asset.
"""
from pathlib import Path
import math,json,hashlib,time
ROOT=Path(__file__).resolve().parents[2];DIR=ROOT/'src/assets/characters';SOURCE=DIR/'sources/makehuman-hm08.obj'
started=time.perf_counter();raw=SOURCE.read_bytes();sha=hashlib.sha256(raw).hexdigest();assert sha=='8e761e6624b8f54536409135d1636da63b32486a90d4897f84e121d144f6fb4c'
verts=[];faces=[];groups={};group=''
for line in raw.decode().splitlines():
 a=line.split()
 if not a:continue
 if a[0]=='v':verts.append(tuple(map(float,a[1:4])))
 elif a[0]=='g':group=a[1]
 elif a[0]=='f':
  ids=[int(t.split('/')[0])-1 for t in a[1:]];groups.setdefault(group,set()).update(ids)
  if group=='body':faces.extend((ids[0],ids[i],ids[i+1]) for i in range(1,len(ids)-1))
def add(a,b):return tuple(x+y for x,y in zip(a,b))
def sub(a,b):return tuple(x-y for x,y in zip(a,b))
def mul(a,s):return tuple(x*s for x in a)
def dot(a,b):return sum(x*y for x,y in zip(a,b))
def norm(a):return math.sqrt(dot(a,a))
def unit(a):return mul(a,1/norm(a))
def cross(a,b):return(a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0])
def joint(name):
 ids=groups['joint-'+name];return tuple(sum(verts[i][k] for i in ids)/len(ids) for k in range(3))
bodyids=groups['body'];low=min(verts[i][1] for i in bodyids);scale=1.94/(max(verts[i][1] for i in bodyids)-low);sections=[]
def profile(center,axis,count,label):
 # Exclude disconnected cross-sections only; shoulders can join the torso.
 axis=unit(axis);u=unit(cross(axis,(0,0,1)));v=unit(cross(u,axis));graph={};points={};source_ids=set()
 for f in faces:
  vv=[verts[i] for i in f];ps=[]
  for a,b in zip(vv,vv[1:]+vv[:1]):
   da=dot(sub(a,center),axis);db=dot(sub(b,center),axis)
   if (da<=0<db) or (db<=0<da):ps.append(add(a,mul(sub(b,a),-da/(db-da))))
  if len(ps)==2:
   source_ids.update(f);ids=[tuple(round(x,6) for x in p) for p in ps]
   for j in [0,1]:points[ids[j]]=ps[j];graph.setdefault(ids[j],set()).add(ids[1-j])
 pending=set(graph);components=[]
 while pending:
  todo=[pending.pop()];component=[]
  while todo:
   a=todo.pop();component.append(a)
   for b in graph[a]:
    if b in pending:pending.remove(b);todo.append(b)
  components.append(component)
 ids=min(components,key=lambda c:sum(norm(sub(points[k],center)) for k in c)/len(c));keep=set(ids)
 p2={i:(dot(sub(points[i],center),u),dot(sub(points[i],center),v)) for i in ids};bounds=[(min(p[k] for p in p2.values()),max(p[k] for p in p2.values())) for k in [0,1]]
 mid=[sum(b)/2 for b in bounds];r=[(b[1]-b[0])/2 for b in bounds];p2={i:tuple((p[k]-mid[k])/r[k] for k in [0,1]) for i,p in p2.items()}
 edges=[(a,b) for a in ids for b in graph[a] if b in keep and a<b];factors=[]
 for i in range(count):
  angle=i/count*math.tau;d=(math.sin(angle),math.cos(angle));hits=[]
  for aa,bb in edges:
   a=p2[aa];b=p2[bb];e=(b[0]-a[0],b[1]-a[1]);den=d[0]*e[1]-d[1]*e[0]
   if abs(den)<1e-10:continue
   t=(a[0]*e[1]-a[1]*e[0])/den;w=(a[0]*d[1]-a[1]*d[0])/den
   if t>0 and -1e-7<=w<=1+1e-7:hits.append(t)
  assert hits,(label,i);factors.append(min(hits))
 sections.append({'label':label,'sourceCenter':center,'sourceAxis':axis,'sectionVertices':len(ids),'components':len(components),'sourceHalfExtentsM':[x*scale for x in r],'sourceCenterOffsetM':[x*scale for x in mid],'rawNormalizedRadii':factors,'crossedTriangleVertexIdsBeforeComponentFilter':sorted(source_ids)})
 return factors
# Q supplies clothing dimensions, Y rows and folds. Source supplies angular shape.
torso_y=[-.15,-.04,.1,.2,.33,.43,.49,.54,.57];torso_blend=[0,0,.65,.7,.7,.6,.35,.15,0]
sleeve_y=[-.643,-.60,-.52,-.43,-.37,-.33,-.29,-.20,-.11,-.04,.035,.065];sleeve_blend=[0,0,.4,.6,.65,.5,.55,.65,.5,.2,0,0]
shoulder=joint('l-shoulder');elbow=joint('l-elbow');hand=joint('l-hand');pelvis=joint('pelvis');neck=joint('neck');torso=[];sleeve=[]
for row,(y,blend) in enumerate(zip(torso_y,torso_blend)):
 if not blend:torso.append([1]*18);continue
 sy=pelvis[1]+y/.6*(neck[1]-pelvis[1]);t=(sy-pelvis[1])/(neck[1]-pelvis[1]);f=profile((0,sy,pelvis[2]+t*(neck[2]-pelvis[2])),(0,1,0),18,'torso-'+str(row));torso.append([round(1+blend*(max(.82,min(1.18,x))-1),6) for x in f])
for row,(y,blend) in enumerate(zip(sleeve_y,sleeve_blend)):
 if not blend:sleeve.append([1]*12);continue
 a,b,t=(shoulder,elbow,-y/.33) if y>=-.33 else (elbow,hand,(-y-.33)/.31);t=max(.08,min(.92,t));t=.34 if row==9 else t
 f=profile(add(a,mul(sub(b,a),t)),sub(a,b),12,'sleeve-'+str(row));sections[-1]['sourceBoneFraction']=t
 # This small shoulder-adjacent ring uses separated upper arm, not joined torso.
 if row==9:assert sections[-1]['components']>=2 and max(sections[-1]['sourceHalfExtentsM'])<.08
 sleeve.append([round(1+blend*(max(.82,min(1.18,x))-1),6) for x in f])
body='// Generated by scripts/characters/generate-body-profile.py; CC0 hm08 contour derivative.\n'
for name,data in [('MIRA_TORSO_PROFILE',torso),('MIRA_SLEEVE_PROFILE',sleeve)]:body+='export const '+name+'='+json.dumps(data,separators=(',',':'))+';\n'
out=DIR/'body-profile-data.js';out.write_text(body)
p={'schemaVersion':1,'role':'npc / Mira only','source':{'file':'sources/makehuman-hm08.obj','sha256':sha,'bytes':len(raw),'url':'https://raw.githubusercontent.com/makehumancommunity/makehuman/a8bc2d54ff0ac92e78ff71431b1023eda42bf482/makehuman/data/3dobjs/base.obj','license':'CC0-1.0','licenseFile':'sources/MAKEHUMAN-LICENSE-ASSETS.md'},'sourceKind':'Artist-authored graphical body, not scan, photo or calibrated anatomy','morphsApplied':[],'generator':{'file':'scripts/characters/generate-body-profile.py','sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()},'output':{'file':out.name,'bytes':len(body.encode()),'sha256':hashlib.sha256(body.encode()).hexdigest()},'registration':{'referenceStatureM':1.94,'uniformScale':scale,'torsoY':'source pelvis + Q rowY/.6 * (source neck - source pelvis); source bbox-centered angular contour mapped to current garment radii','armAxialScale':[.33/(norm(sub(elbow,shoulder))*scale),.31/(norm(sub(hand,elbow))*scale)],'leftRight':'Left source sleeve contour mirrored for Q arm-0; no demographic/morph change','shoulderRow9':'Samples separated upper arm at source fraction .34, then blends .2 to fixed shoulder rows. Direct row9 source plane would include torso, not an isolated sleeve.','radialClamp':[.82,1.18],'torsoBlend':torso_blend,'sleeveBlend':sleeve_blend},'clothing':'Q garment radii and folds define an authored ease envelope, independently of naked source. Bounded source angular factors modulate it. These differences are not measured fabric thickness. No underlying nude body is introduced.','unchanged':'All bones/row Y/skin weights/head/neck/hands/materials. Torso first2+last row, sleeve first2+last2 position rows fixed. 483 vertices/816 triangles.','qualityBoundary':'New numeric candidate; old unrecovered v42 is not acceptance evidence. No rendered cloth/seam/motion or PS4-quality pass.','sections':sections}
(DIR/'body-profile-provenance.json').write_text(json.dumps(p,indent=2)+'\n');print(json.dumps({'generationSeconds':time.perf_counter()-started,'bytes':len(body.encode()),'sections':len(sections),'sourceTriangles':len(faces),'sha256':p['output']['sha256']}))
